### ISSUE TITLE
File names are converted to lower case

### ISSUE THREAD

**Issue by epeli** [dutchcoders/transfer.sh#10]
`curl -v -T Gemfile.lock transfer.sh` results in `https://transfer.sh/:key/gemfile.lock` even thou curl properly sends the PUT request with correct casing.

From the log output: 

```
> PUT /Gemfile.lock HTTP/1.1
```

This gets pretty annoying when downloading the file again.

Awesome service anyway. Thanks!

**Comment by probonopd** [comment]
Ping :-)

**Comment by probonopd** [comment]
Is there still a chance of this being implemented? Thanks.

**Comment by cristian0** [comment]
+1
