### ISSUE TITLE
Launching docker version of the server over https

### ISSUE THREAD

**Issue by GuillaumeBlin** [dutchcoders/transfer.sh#101]
Hi,
i've been trying along few stuff to get the transfer.sh server working only with https and using the docker image but was not successful at all.
Would you mind adding an example on how to launch it with https support ?
I've naively tried:
`docker run -v /tmp/truc:/tmp --publish 8081:443 dutchcoders/transfer.sh:latest --tls-listener :443 --provider local  --basedir /tmp/
2017/10/16 14:47:24 Transfer.sh server started.
listening on port: :8080
using temp folder: /tmp
using storage provider: local
2017/10/16 14:47:24 ---------------------------
panic: open : no such file or directory

goroutine 143 [running]:
panic(0x833740, 0xc420730030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/dutchcoders/transfer.sh/server.(*Server).Run.func5(0xc420182750, 0xc4206fd4a0)
	/go/src/github.com/dutchcoders/transfer.sh/server/server.go:353 +0x12c
created by github.com/dutchcoders/transfer.sh/server.(*Server).Run
	/go/src/github.com/dutchcoders/transfer.sh/server/server.go:355 +0x169f`
It seems it does not like when --listener is not given.
Any help appreciate.
Best
NB: Great job by the way ! We are using it for a C programming classroom where we ask for some image manipulation and it helps us by providing a temporary storage for the result images.

**Comment by aspacca** [comment]
@GuillaumeBlin , currently `--listener` seems to be mandatory: you can add an optional tls listener but that won't replace the plain http listener. I will look in a solution in the next days
