### ISSUE TITLE
File not found errors

### ISSUE THREAD

**Issue by probonopd** [dutchcoders/transfer.sh#103]
Today, getting lots of "File not found" errors:

![screenshot_2017-11-06_01-37-52](https://user-images.githubusercontent.com/2480569/32420960-35c47ace-c293-11e7-9429-d176b892308f.png)

Cc @sithlord48 who also experienced the same today.

**Comment by nl5887** [comment]
From what I can see the link expired 4th of nov.

**Comment by probonopd** [comment]
https://transfer.sh/FB0l0/Subsurface-44007ce-x86_64.AppImage shows the HTML page, but the download is unavailable. According to https://travis-ci.org/probonopd/subsurface/jobs/299800783#L6475 this was uploaded there just 39 minutes ago.

**Comment by probonopd** [comment]
Same for https://transfer.sh/aFQ0o/Subsurface-44007ce-x86_64.AppImage

**Comment by probonopd** [comment]
Here are more examples:
https://download.supertux.org/#linux-files

**Comment by probonopd** [comment]
Today, getting

```
me@host wget "https://transfer.sh/Bqw0v/ImageMagick-git.4f1716e-x86_64.AppImage"
--2017-11-12 18:52:47--  https://transfer.sh/Bqw0v/ImageMagick-git.4f1716e-x86_64.AppImage
Resolving transfer.sh (transfer.sh)... 2001:bc8:4400:2200::3c29, 51.15.129.136
Connecting to transfer.sh (transfer.sh)|2001:bc8:4400:2200::3c29|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-11-12 18:52:48 ERROR 500: Internal Server Error.
```

**Comment by KurtPfeifle** [comment]
I've got this same error about 5 minutes ago:
<pre>
$~> wget https://transfer.sh/Bqw0v/ImageMagick-git.4f1716e-x86_64.AppImage
--2017-11-12 19:06:00--  https://transfer.sh/Bqw0v/ImageMagick-git.4f1716e-x86_64.AppImage
Resolving transfer.sh (transfer.sh)... 51.15.129.136, 2001:bc8:4400:2200::3c29
Connecting to transfer.sh (transfer.sh)|51.15.129.136|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-11-12 19:06:02 ERROR 500: Internal Server Error.
</pre>
