### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by kaundinya5** [dutchcoders/transfer.sh#108]
I'm trying to upload a file to transfer.sh but it keeps saying 443 connection refused.

**Comment by dmigous** [comment]
+1

**Comment by drozdvadym** [comment]
+1

**Comment by sedubois** [comment]
+1

`Failed to connect to transfer.sh port 443: Operation timed out`

**Comment by vitorgalvao** [comment]
Site is up again, and has been for a few days. This can be closed.
