### ISSUE TITLE
hello, I am fresh bird to Go, I want to know how I can change the web index page?

### ISSUE THREAD

**Issue by goxofy** [dutchcoders/transfer.sh#110]
Thank you very much!

**Comment by edhardie** [comment]
Hi @goxofy, having just been in the same boat as you I thought I'd pitch in with an answer in case anyone else comes across this.

Repo for the front end source is here - https://github.com/dutchcoders/transfer.sh-web

Any changes you make will need to be complied down into a bindata_gen.go file, if you're just editing the index.html file all you'll need to do is make sure go is installed and run `go generate .` from the directory you cloned into. This will place your bindata file in the current directory, which then needs to be copied over to replace the bindata_gen.go file in this repo - https://github.com/dutchcoders/transfer.sh/blob/master/vendor/github.com/dutchcoders/transfer.sh-web/bindata_gen.go

If you're editing CSS and JS you'll need to compile assets using `grunt build` before you run `go generate .`, ensuring npm and bower dependencies are installed. 

Hope that helps.
