### ISSUE TITLE
File upload fails

### ISSUE THREAD

**Issue by Destroyer** [dutchcoders/transfer.sh#112]
I am trying to upload 1GB file but right at the start I get this error: `Error (0) during upload of file`  . Can you please fix it?

**Comment by Taxel** [comment]
Same here with a 4.04 GB mp4 file

**Comment by Favna** [comment]
With a 2.47 7z file I got this error "explaining" it. Now i'm on a quest to find some official statement from dutchcoders. Transfer.sh has been my favorite host to share files for so long this just feels so dumb:

```
Due to abuse we've limited max upload size. Thank the pirates!
```

**Comment by Favna** [comment]
Well I found an official statement... Apparently Transfer.sh has been enitrely taken down. 

https://twitter.com/dutchcoders/status/913835197237465089

**Comment by techburgher** [comment]
It seems like the ContentLength is capping out at 4294967295 bytes, preventing a file larger than this from properly uploading.

I see the following logged by the server:

2018/03/02 14:29:25 Uploading cA3TH 10g.bin 4294967295 application/octet-stream

The transfer craps out after uploading 4294967295 bytes of my 10 GB file. How would one go about correcting this?

**Comment by Favna** [comment]
@techburgher as stated in the tweet I linked in my comment above, you cannot upload to transfer.sh at all anymore. Not at 1 gigabyte, not at 5, not at 10, nothing. The service is presumably down.

filetransfer.io is a good alternative

**Comment by techburgher** [comment]
@Favna I'm running a local copy of the server and am running into this issue.

**Comment by Favna** [comment]
Oh.. well ok. Maybe add such details right away the next time. I would recommend reading [this article on writing proper github issues](https://wiredcraft.com/blog/how-we-write-our-github-issues/) or this [etiquette article](http://www.defmacro.org/2013/04/03/issue-etiquette.html)

**Comment by aspacca** [comment]
@techburgher cannot reproduce locally both with local and gdrive storage (I don't have an s3 account to test on). Anyway the content-lenght you see in the output of the server is calculated before sending to the storage and it comes from the `Content-Length` header sent from the client (unless the client sends `-1`, in this case the value is calculated according to the size of the data copied to a tmp file buffer)

what storage do you use? can you run curl with verbose flag and past the output?
