### ISSUE TITLE
Direct download link

### ISSUE THREAD

**Issue by cgebe** [dutchcoders/transfer.sh#113]
Is it possible to obtain a direct download link or some option to activate it?

**Comment by arifpedia** [comment]
@cgebe : I think it's already direct link

**Comment by cgebe** [comment]
There is no option to get a ddl on transfer.sh. Since the self-hosted variant is an identical copy of transfer.sh, there isn't a ddl either.

Would be great to have this option atleast when self-hosting.

**Comment by arifpedia** [comment]
**Right click** on a link and select **Save link as**. You also can using wget, curl, aria2 and other download manager. 
Demo: https://transfer.sh/CHpeY/qterminal_id.po

**Comment by cgebe** [comment]
Thank you for you advice. Guess i was just to focused on not getting a ddl via browser. However via cli tools it works like a charm.
