### ISSUE TITLE
Alternative solution now that transfer.sh is dead IN HERE

### ISSUE THREAD

**Issue by gingerbeardman** [dutchcoders/transfer.sh#116]
Check out these alternatives...

**All**
- simple bash script install rather than alias
- link copied to clipboard on successful upload (macOS only)

---

**file.io**
https://gist.github.com/gingerbeardman/a7737e4c89fccab8605f8538ddaeec0d
- uses https://file.io
- expires after one single download
- default but configurable expiry duration

---

**0x0.st**
https://gist.github.com/gingerbeardman/5398a5feee9fa1e157b827d245678ae3
- uses https://0x0.st
- unlimited downloads
- larger files expire after a month, small files expire after a year

**Comment by Octolus** [comment]
Cheers.

**Comment by xNicklaj** [comment]
How do I use file.io with wget instead of curl?

**Comment by mihailescu2m** [comment]
curl -T /path/to/file https://oshi.at

(see https://oshi.at/cmd)

**Comment by HemanthJabalpuri** [comment]
temp.sh
