### ISSUE TITLE
example on home page has extraneous echo

### ISSUE THREAD

**Issue by dmd** [dutchcoders/transfer.sh#121]
![image](https://user-images.githubusercontent.com/41439/41678976-abadaa3a-749a-11e8-98bc-edaf0da0cf31.png)

`Usage:\necho transfer ` should just be `Usage:\ntransfer `

**Comment by aspacca** [comment]
@qoomon you can open a PR on https://github.com/dutchcoders/transfer.sh-web and I will merge

the files are https://github.com/dutchcoders/transfer.sh-web/blob/master/src/index.txt and https://github.com/dutchcoders/transfer.sh-web/blob/master/src/index.html

I see you already commented on the gist with the version without tmpfile

**Comment by qoomon** [comment]
@aspacca okay.
