### ISSUE TITLE
New Icon for Transfer.sh

### ISSUE THREAD

**Issue by Yasujizr** [dutchcoders/transfer.sh#122]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by nl5887** [comment]
Hi, that's great! Looking forward to your ideas.

**Comment by Yasujizr** [comment]
![untitled-3](https://user-images.githubusercontent.com/36993664/41936824-23029810-7997-11e8-95ea-276502fad670.jpg)


I designed two examples based on the <> signs.

**Comment by Yasujizr** [comment]
![sunumtransfer](https://user-images.githubusercontent.com/36993664/41995616-1f92fc1e-7a5b-11e8-9b20-79fe2e04c63a.jpg)

**Comment by ManuCart** [comment]
I vote for the first.
Love your work

**Comment by Yasujizr** [comment]
@ManuCart Thank you, if you need a logo you can contact me.
