### ISSUE TITLE
Add domain name as parameter...

### ISSUE THREAD

**Issue by gufertum** [dutchcoders/transfer.sh#139]
I run the docker behind a proxy and the returned path still contains the localhost with the local port.
It would be nice to have a parameter to overrule this when starting the docker container...

**Comment by gufertum** [comment]
I just created a pull request with the changes...
https://github.com/dutchcoders/transfer.sh/pull/140

**Comment by aspacca** [comment]
@gufertum I don't think that adding one or more parameters is the right solution

we should address the problem in server/handlers.go:467 using http header sent by the proxy.
I cannot test the current behaviour at the moment but will do in the next few days

**Comment by gufertum** [comment]
Closed: setting up apache properly, fixed the issue (ProxyPreserveHost On)
