### ISSUE TITLE
ShareX

### ISSUE THREAD

**Issue by Fatulatti** [dutchcoders/transfer.sh#144]
Hey there,
Currently trying to setup ShareX with clone'd Transfer.sh.
Currently, my config looks like this:
![grafik](https://user-images.githubusercontent.com/34114942/42719640-a0675a0e-8719-11e8-93c6-60df216ed226.png)

But the server prints following error:
2018/07/14 01:54:36 Uploading BY1lI . 60641 multipart/form-data; boundary=--------------------8d5e93d84df3fd6
open /tmp/BY1lI: is a directory2018/07/14 01:54:36 Error putting new file: open /tmp/BY1lI: is a directory
2018/07/14 01:54:36 46.84.98.155:52976 - - [2018-07-14T01:54:36Z] "POST / HTTP/1.1" 500  "" "ShareX"

**Comment by aspacca** [comment]
@Fatulatti I don't know ShareX, but the problem seems that transfer.sh is trying somehow to upload a directory to the tmp folder instead of the file. How do you send the file to transfer.sh?

**Comment by altaha4water** [comment]
شكراً على حسن تعاونكم معن

**Comment by altaha4water** [comment]
www.atyaf-water.com

**Comment by N6UDP** [comment]
@Fatulatti this should be resolved by #155 -- ShareX is attempting a POST w/multipart form data.
