### ISSUE TITLE
transfer.sh is  offline?

### ISSUE THREAD

**Issue by cnrat** [dutchcoders/transfer.sh#158]
Looks like the site is down. Can not access to it.

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7_5.1 <<>> +trace transfer.sh
;; global options: +cmd
.                       3900    IN      NS      k.root-servers.net.
.                       3900    IN      NS      l.root-servers.net.
.                       3900    IN      NS      m.root-servers.net.
.                       3900    IN      NS      a.root-servers.net.
.                       3900    IN      NS      b.root-servers.net.
.                       3900    IN      NS      c.root-servers.net.
.                       3900    IN      NS      d.root-servers.net.
.                       3900    IN      NS      e.root-servers.net.
.                       3900    IN      NS      f.root-servers.net.
.                       3900    IN      NS      g.root-servers.net.
.                       3900    IN      NS      h.root-servers.net.
.                       3900    IN      NS      i.root-servers.net.
.                       3900    IN      NS      j.root-servers.net.
.                       3900    IN      RRSIG   NS 8 0 518400 20181003170000 20180920160000 41656 . GpkbUrPtGfSlssiDMUtjW7cJF9Rob7hS53dXt0+IPOAl/rokV1zhveA1 Gug1ZP95HiqoNMMYXUjHr1yHthtoJkQ+7ezKZdN1PNFH76OkNP510V/M JneqeSGOgqK34k83JbYh1pt7bC9fTGkD5Yr5ML+GNFikwrlDDVEupezD cEpyrP6k934Psr70Kl5Yp1u0SiHace+MJxj5dQjagN3Tc73I5Yu9SP+m JpACqquhBllmqZppBVaCY9rOqAyW8he0fi85NO+9FawiYO+N+QPXrCbW DKMc1YFH6LlFRso9739V2NweQ8+wM3595sYoldcNoeEqbu/rbzOZImaV +W0WEg==
;; Received 525 bytes from 210.188.224.11#53(210.188.224.11) in 11 ms

sh.                     172800  IN      NS      ns-a3.sh.
sh.                     172800  IN      NS      c0.nic.sh.
sh.                     172800  IN      NS      ns-a1.sh.
sh.                     172800  IN      NS      b0.nic.sh.
sh.                     172800  IN      NS      a0.nic.sh.
sh.                     172800  IN      NS      a2.nic.sh.
sh.                     86400   IN      DS      55297 8 2 BA339AD6E081DAD292A3F473CBDD5ADC53A0222769A7C6125F506DD6 A813787F
sh.                     86400   IN      DS      6040 8 2 AB4FEB07A4A5C297A747B7C0CC0616401A3BF6D658AF8408F0207FFF D4B4A57B
sh.                     86400   IN      DS      55297 8 1 59E1077EFCF663D4E2B3DB25A170C735786793EF
sh.                     86400   IN      RRSIG   DS 8 1 86400 20181003170000 20180920160000 41656 . Pg2EpVOzoaQrhyerb1HU4BwzzAw942or32bHbJMXtS5GMKA7VGzdGQRR k46gWqAgOoZmPoGn3/DVsVKxYlBeLYzBdYNhSjBk1OrJvUDTfolsFhL0 KYzGYWcyX7QKYRumqVkD4Hc+WdZ/GkmyT5H3AQ4a0TEnZk7ReCIKm8Qs tPMp7nNHLnFsmIgZ5ai/BAQuWqxXw3NjM59Wa2ZhkitUgOjN60E+TPWw eT6liRjSsI1ZtzqitpTxRzD/kCrW6JJNL9ciDltdS+jc+XY5G0mySon4 RxCaZPGLirLLR5falycveUNdQyLxogVqd/z1upFWQouzus+0poaq02Zq rAU2Ig==
;; Received 807 bytes from 192.36.148.17#53(i.root-servers.net) in 7 ms

transfer.sh.            86400   IN      NS      ns-491.awsdns-61.com.
transfer.sh.            86400   IN      NS      ns-808.awsdns-37.net.
transfer.sh.            86400   IN      NS      ns-1036.awsdns-01.org.
jer2l9rq4plbvig56tiibt8via9suspf.sh. 900 IN NSEC3 1 1 1 D399EAAB JIFULRSVHGMH7U0009N6PBVI36IC65EU NS SOA RRSIG DNSKEY NSEC3PARAM
jer2l9rq4plbvig56tiibt8via9suspf.sh. 900 IN RRSIG NSEC3 8 2 900 20181012020755 20180921010755 42529 sh. IhS3yo97xX0nZHMXWJfBUzAkiGzrrjYFfNk5pv/SylUnMNW+/nexX0bT 2Vjvo3RTegMDKWt380/vCvGJm8F/NM8bC9MMbpKx4yBwbsHLXgGd7oQI nL3ysiO/aiEtZOVevFgGa1dVOzXTzNn72Y33OmPlaem0+XTmjFCNbuVa raY=
7t39rrlehom6akg0jaevvv6lgn4fon7n.sh. 900 IN NSEC3 1 1 1 D399EAAB 848RVRS9GSQ5J277JC91OGQQKO0L0I44 NS DS RRSIG
7t39rrlehom6akg0jaevvv6lgn4fon7n.sh. 900 IN RRSIG NSEC3 8 2 900 20181008152509 20180917142509 42529 sh. BmUMV8kTFYAn4eyjGS/a3sCsAfueO3H5EnxjOdGVfipv/oQBmYdesESY XLUXqtkyqvlDTki7QzNr6SIWHWGsC2VGYxGOtw82HWS9JP731k9vmW2n lsbTpvONRfoAftKeU+7Ba+8p2lLCg/FgiFEs5RXIY4OyIrRpNd6SaOfQ X6g=
;; Received 634 bytes from 65.22.160.9#53(a0.nic.sh) in 4 ms

transfer.sh.            300     IN      A       185.216.24.82
transfer.sh.            172800  IN      NS      ns-1036.awsdns-01.org.
transfer.sh.            172800  IN      NS      ns-1680.awsdns-18.co.uk.
transfer.sh.            172800  IN      NS      ns-491.awsdns-61.com.
transfer.sh.            172800  IN      NS      ns-808.awsdns-37.net.
;; Received 196 bytes from 205.251.195.40#53(ns-808.awsdns-37.net) in 158 ms

**Comment by ohhayley** [comment]
Same problem
curl: (7) Failed to connect to transfer.sh port 443: Connection timed out

**Comment by hanwckf** [comment]
curl: (7) Failed to connect to transfer.sh port 443: Connection timed out

**Comment by Neko250** [comment]
bump ! same here

**Comment by cnrat** [comment]
It's now back online. Close this issue.

**Comment by akshaynexus** [comment]
again its down
