### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by 0xE02B7** [dutchcoders/transfer.sh#160]
Hello, 
I am new to Go and therefore don't exactly know how to build this tool.

go version
go version go1.10.1 linux/amd64

/var/www/_tests/transfer.sh# ls
cmd  extras  lock.json  main.go  manifest.json  README.md  server  Vagrantfile  vendor

echo $GOROOT
/usr/lib/go-1.10/

echo $GOPATH
/var/www/_tests/transfer.sh/

go run main.go -provider=local --listener :8080 --temp-path=/tmp/ --basedir=/tmp/
main.go:3:8: cannot find package "github.com/dutchcoders/transfer.sh/cmd" in any of:
	/usr/lib/go-1.10/src/github.com/dutchcoders/transfer.sh/cmd (from $GOROOT)
	/var/www/_tests/transfer.sh/src/github.com/dutchcoders/transfer.sh/cmd (from $GOPATH)

**Comment by aspacca** [comment]
hi @0xE02B7 , GOPATH must point to a directory with inside a path like `src/github.com/dutchcoders/transfer.sh`

so you should decide what's your GOPATH, create a `src` directory inside and then clone this repository in `github.com/dutchcoders/transfer.sh`

let me know if you solved
