### ISSUE TITLE
Files larger than 1GB fail to upload

### ISSUE THREAD

**Issue by xlJohnnyIcelx** [dutchcoders/transfer.sh#161]
Whenever I try to upload any file larger than 1GB it fails to upload. This is the case whether I use the web uploader or use ShareX

**Comment by aspacca** [comment]
@xlJohnnyIcelx are you referring to https://transfre.sh?

**Comment by xlJohnnyIcelx** [comment]
Yes I am referring to https://transfer.sh

**Comment by aspacca** [comment]
then I cannot give you any support, sorry: I'm only the maintainer of the codebase that run on that website but the website is managed by @nl5887
