### ISSUE TITLE
Log, option --log, how to log in custom file?

### ISSUE THREAD

**Issue by jguidini** [dutchcoders/transfer.sh#167]
Hi, I installed transfer.sh inside our cloud and was great! But I tried several ways to log outside syslog. In my case rsyslog on a Debian 8 amd64. I want to log directly in a file in a custom path. 
I can do a syslog filter, of course, but I want understend why cannot do a custom path with --log option, what Im doing wrong :-).

My command line is:
 /opt/transfer_sh/bin/transfer_sh --temp-path=/transfer_sh/temp --basedir=/transfer_sh/dados --listener :8081 --provider=local --log=/var/log/transfer_sh/transfer_sh.log --clamav-host=unix:/tmp/clamd.socket --virustotal-key=<key_secret> --log=/var/log/transfer_sh/transfer.log

Thanks!

**Comment by aspacca** [comment]
@jguidini you're not doing anything wrong. it seems the --log option is not actually applied, also some log are not directed to logger but directly printed to the stdout. I will address the problem in the next days
