### ISSUE TITLE
Customizable frontend

### ISSUE THREAD

**Issue by telatin** [dutchcoders/transfer.sh#168]
I understand that the main website https://transfer.sh will be closing soon, unfortunately.
I tried the Docker container on a VM and it works very well, but it's odd that the homepage is branded "transfer.sh", and gives static examples of commands assuming that domain.

I think the source files for the front end should be provided to update them.

Thanks

**Comment by mckaygerhard** [comment]
umm the source files are not in the main repository?

**Comment by mckaygerhard** [comment]
https://github.com/dutchcoders/transfer.sh-web i think!

**Comment by telatin** [comment]
Thanks! I will try that parameter.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bandicootdancing** [comment]
Options with some instructions would be appreciated. I don't see any normal instructions on setting this up without docker. I'm very new to docker so I'm almost lost at the moment with combining the two containers. Can someone write up some instructions on how to customize the transfer.sh-web along with this transfer.sh container? Do they both need to be used together? 

I've seen other projects have a build process for the docker container. It'd be awesome to edit the frontend as needed then build if possible.

**Comment by aspacca** [comment]
@bandicootdancing transfer.sh-web is a go dependency of transfer.sh. In the first repository there should be full  instruction on how to build the frontend with grunt and generate the go bindata depdency. After that you only need to copy the transfer.sh-web directory in the proper vendor position of transfer.sh, if you didn't already worked from there.

If you want to user the `--web-path` on a transfer.sh docker container you just need to mount the content of the grunt generated frontend on the container. this mount can come or not from another container, but it is static content and I wouldn't see the reason for putting it in a container. Be aware that you only need the `dist` directory (target of the grunt build) of transfer.sh-web to be mounted, that's the reason why transfer.sh-web has no Dockerfile

**Comment by aspacca** [comment]
@bandicootdancing I see there are already instructions on transfer.sh-web readme how to setup what I've just explained:
```
docker run -d -v /folder:/uploads -v /folder/dist:/webapp --publish 5000:8080 dutchcoders/transfer.sh:latest --provider local --basedir /uploads --web-path /webapp/
```

obviously `/folder` and `/folder/dist` are just example: you can put whatever path you need for your setup and they don't even need to be nested like in the example
