### ISSUE TITLE
Document supported headers on transfer.sh

### ISSUE THREAD

**Issue by marcelstoer** [dutchcoders/transfer.sh#177]
One example on https://transfer.sh/ uses `-H "Max-Downloads: 1" -H "Max-Days: 5"`. I can guess what those headers do but it would be nice if they were properly documented somewhere. Suggestion: README.md.

**Comment by aspacca** [comment]
@marcelstoer yes, I planned to add the full documentation of the supported headers in request and response in the README.md but I haven't had time yet. Feel free to open a PR for it

**Comment by marcelstoer** [comment]
> Feel free to open a PR for it

I would if I knew the answers. However, since I would have to dig into a code base of a language I'm not familiar with this wouldn't be effective at all.

**Comment by aspacca** [comment]
fixed with #225
