### ISSUE TITLE
Q: how to see TTL of a file?

### ISSUE THREAD

**Issue by marcelstoer** [dutchcoders/transfer.sh#178]
Only slightly related to #177.

After I uploaded a file using `curl -H "Max-Days:2" ...` is there a way to see/learn how much more time until the file is destroyed? I would have expected to see that at `https://transfer.sh/UjsCv/my_file.txt`.

**Comment by aspacca** [comment]
@marcelstoer there's no info about the remaining days/download hits on the front-end, it would be indeed nice to add this feature and I will do that as soon as I have time.
Said that, the hosting service transfer.sh is not in sync with the source code so it can be that the feature won't be available there. I'm the maintainer of the source code, but I have no control to the hosting service

**Comment by mckaygerhard** [comment]
there's a year about this issue and seems some work was done at #234 pull request ..

**Comment by aspacca** [comment]
@mckaygerhard thanks, I completely lost track of this issue. I can close since #234
