### ISSUE TITLE
Support for mkv video files

### ISSUE THREAD

**Issue by orschiro** [dutchcoders/transfer.sh#18]
Hi there,

Many thanks for transfer.sh! I regularly use it to share some files.

Just now I wanted to share a screencast that I had created with `simplescreenrecorder` on my Linux machine: https://transfer.sh/RzaoH/screencast.mkv

The default format is `mkv` which currently does not seem to be supported. 

Would it be possible to support `mkv` files?

Thankfully,

Robert

**Comment by johnko** [comment]
According to http://www.matroska.org/news/webm-matroska.html

webm is a subset of mkv

So what might work is serving `*.mkv` files with a Content-Type `video/webm` as suggested in http://stackoverflow.com/questions/9622726/html5-video-can-play-mkv-files/29438223#29438223

So maybe after [line 165](https://github.com/dutchcoders/transfer.sh/blob/master/transfersh-server/main.go#L165), add:

```
mime.AddExtensionType(".mkv", "video/webm")
```

**Comment by aspacca** [comment]
@orschiro is this still an issue?

**Comment by orschiro** [comment]
@aspacca not anymore. Thanks for the reminder! Closing...
