### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by notramo** [dutchcoders/transfer.sh#180]
I have read #22.
What about allowing creating accounts, and if a file is uploaded in an account, then permit raw access?
If GitHub account should be used for transfer.sh account creation, unethical use of the service could be lowered.

**Comment by mckaygerhard** [comment]
well i think account will complicated more that simple ways of the thinks!

also account will convert this into a kind of owncloud/netxcloud!

**Comment by notramo** [comment]
It would only attach an username to transfers for tracking.

**Comment by mckaygerhard** [comment]
umm i understand what do you want! like we-transfer does! but that will complicated the things in any case.. i means will be not ease!

**Comment by notramo** [comment]
Yes, it would be similar to We-Transfer, but it would use a permanent account.

**Comment by mckaygerhard** [comment]
@notramo you can review the pull https://github.com/dutchcoders/transfer.sh/pull/105/files and see or adapt for your needs! personally this will convert into a nextcloud/owncloud system but i also understand your point of view!

**Comment by mckaygerhard** [comment]
@notramo you can review the pull https://github.com/dutchcoders/transfer.sh/pull/105/files and see or adapt for your needs! personally this will convert into a nextcloud/owncloud system but i also understand your point of view!

also that was limited implemented into https://github.com/dutchcoders/transfer.sh/pull/127

**Comment by aspacca** [comment]
@notramo what's the problem you have exactly?

@mckaygerhard #105 was closed by the author and implemented properly in #127

**Comment by notramo** [comment]
Authenticated uploads should have a raw content URI, which don't use the web wrapper.

**Comment by aspacca** [comment]
@notramo what issue are you facing? what are you trying to do that you cannot?

**Comment by notramo** [comment]
#22

**Comment by mckaygerhard** [comment]
swo i understand, raw links can be offered but with authentication, so abused could be avoid! right?

**Comment by notramo** [comment]
@mckaygerhard Yes. Authenticated uploads should have raw links.

**Comment by aspacca** [comment]
@notramo , I repeat the question for the last time: what issue are you facing? what are you trying to do that doesn't work?
#22 is not an issue on itself

**Comment by notramo** [comment]
I want to have raw links. Authentication can be a solution against abuse.

**Comment by mckaygerhard** [comment]
yeah, it's a great idea that solved the raw links problem, as i said in previous comment!

**Comment by aspacca** [comment]
@notramo you have "raw link" available with curl

**Comment by mckaygerhard** [comment]
> @notramo you have "raw link" available with curl

umm so the software detect the agent and property offerts the raw link?

and i think you dont understand that @notramo said! @aspacca : i think its that raw links can also be available for browsers agents too! but autenticated to avoir abuse

well i think!

**Comment by notramo** [comment]
How can phone users use curl?
