### ISSUE TITLE
Due to abuse we've limited max upload size. Thank the pirates!

### ISSUE THREAD

**Issue by zafai** [dutchcoders/transfer.sh#181]
I just tried to upload a file and got this error message:
`Due to abuse we've limited max upload size. Thank the pirates!`
What is the current max upload size?

**Comment by aspacca** [comment]
not related to source code of the project

**Comment by mckaygerhard** [comment]
umm maybe the right question its "what do you use to have that message?"  @aspacca and we then need to have a template of issues

**Comment by jiqing112** [comment]
Maybe the homepage needs to be modified

![snipaste_2019-01-12_23-16-08](https://user-images.githubusercontent.com/17674011/51074935-1007f680-16c0-11e9-9760-f47663f1dd27.png)

**Comment by Imparium** [comment]
Indeed, trying to upload a 7gb file can it is not possible.

**Comment by jiqing112** [comment]
> Indeed, trying to upload a 7gb file can it is not possible.

After all, it is a public service, and people have a cost.

**Comment by Imparium** [comment]
Yes, but the homepage states the maximum of 10gb, then it should be updated to the real maximum filesize.

**Comment by alexbalkan** [comment]
Very convenient service. Why cut everyone? If the pirates are to blame, then you can somehow ban such people. You can make a purely symbolic payment.

**Comment by gitSambhal** [comment]
What is the max limit?

**Comment by alexbalkan** [comment]
Good day !
Today I think 1GB is enough. Maximum no more than 10GB. Today, the service
does not work at all. I wanted to know what happened. Is the service dead?
Thanks

ср, 20 нояб. 2019 г. в 11:56, gitSambhal <notifications@github.com>:

**Comment by AlpixTM** [comment]
Currently limited to 1GB, no MB more…
