### ISSUE TITLE
Alternative URL to transfer.sh

### ISSUE THREAD

**Issue by marcelstoer** [dutchcoders/transfer.sh#182]
Some MX hosters reject the transfer of emails that contain transfer.sh URLs

> SMTP error from remote mail server after end of data:
554 5.7.1  Your message contains a domain on our domain block list

Is there an alias/secondary domain we could use or do I need to build a redirect from my own domain?

**Comment by aspacca** [comment]
@marcelstoer I have no control on the hosting service at transfer.sh and I cannot help.
you may want to reach directly https://storj.io/

**Comment by marcelstoer** [comment]
Do you have a specific contact there? I reached out to them by email and Twitter and didn't get a reply to either.
