### ISSUE TITLE
ambigous project, clarifications and questions: transfer.sh service/backend ?

### ISSUE THREAD

**Issue by mckaygerhard** [dutchcoders/transfer.sh#183]
PRELIMINARY: the project transhfer.sh seems are a service and also a binary program client, that can made both task, serve for uploading files and also to download files from..  and seems transfer.sh-web its a separate project that uses that program as a backend, right? 

if you clafify for me those i can provide better documentation (stating at the wiki project and later after you can reviewed, i can provide a pull request with a better README):

1) the README seems does not clarify that, its said "run" and make it feel like the binary compiled its a program client to upload files only to "transfer.sh" url and some others.. and dont point that itselft its also a service for storage (with the paramet "provider" in "local" mode???), that's right?

2) the README does not point if the other project "transfer.sh-web" its in same behaviour, i mean, in examples are using the url "transfer.sh" but does not clarify that the project does not generated that webside and the code are only a backend (either or not service or client nly or both) ...

3) also, the proyect are under same "team" (duchcoders) but seems (as i can see in the other) are "away" of the development of the "transfer.sh-web" project, does not point of are in sync, etc etc

4) seems compilation on both need external resources (need internet connection) but does not clarify that! so packagin for OS distribution are very complicated if are true! like linux (debian, alpine, arch) , freebsd, haiku, etc

**Comment by mckaygerhard** [comment]
please dont close until are in sync with dutchcoders/transfer.sh-web#16

**Comment by aspacca** [comment]
@mckaygerhard transfer.sh and transfer.sh-web are actually in sync. the second is bundled with the first as dependency in vendor package. I'm discussing with @nl5887 about how to improve the dependency between the two projects.
I'm going to close this ticket since it's not adding any value: if you can address specific problem in the documentation we can handle, or you can just open a PR to improve it directly

**Comment by mckaygerhard** [comment]
**i mean, i want to offically be clear before send a PR to yours** umm by example see the 2 and 4 that point important things:

1. on both projects  the README seems does not clarify what its what, its said "run" and make it feel like the binary compiled its a program client to upload files only to "transfer.sh" url and some others.. and dont point that itselft its also a service for/to storage (with the paramet "provider" in "local" mode???), that's right?
2.  the README does not point what are that generated what i mean, in examples are using the url "transfer.sh" but does not clarify that the project does not generated that webside and the code are only a backend (either or not service or client nly or both) ... and the webpage (with the wonderfully script that can upload with a simple drag on drop) are generated with transhfer.sh-web
3. `->` that was answered in both thanks, see next question:
4. seems compilation on both need external resources (need internet connection) but does not clarify that! so packagin for OS distribution are very complicated if are true! like linux (debian, alpine, arch) , freebsd, haiku, etc, in that you pointed that "the second its bundled with the firts" what thoes mean exactly, i taking about by example for generate the ddist on web need a `go get -u github.com/shuLhan/go-bindata/...` but noted that due problems in versioning (golang has some probles with that) many project prefer handle nside the sourdces, i propose a git submodule! a git submodule does the same but in specfific git commit or codebase...

**Comment by mckaygerhard** [comment]
hi @aspacca thanks but still only aswered one question: i'll try to be more specific: **i mean, i want to offically be clear before send a PR to yours** umm by example see the 2 and 4 that point important things:

1. on both projects  the README seems does not clarify what its what, its said "run" and make it feel like the binary compiled its a program client to upload files only to "transfer.sh" url and some others.. and dont point that itselft its also a service for/to storage (with the paramet "provider" in "local" mode???), that's right?
2.  the README does not point what are that generated what i mean, in examples are using the url "transfer.sh" but does not clarify that the project does not generated that webside and the code are only a backend (either or not service or client nly or both) ... and the webpage (with the wonderfully script that can upload with a simple drag on drop) are generated with transhfer.sh-web
3. `->` that was answered in both thanks, see next question:
4. seems compilation on both need external resources (need internet connection) but does not clarify that! so packagin for OS distribution are very complicated if are true! like linux (debian, alpine, arch) , freebsd, haiku, etc, in that you pointed that "the second its bundled with the firts" what thoes mean exactly, i taking about by example for generate the ddist on web need a `go get -u github.com/shuLhan/go-bindata/...` but noted that due problems in versioning (golang has some probles with that) many project prefer handle nside the sourdces, i propose a git submodule! a git submodule does the same but in specfific git commit or codebase...
