### ISSUE TITLE
transfer.sh menu entry open firefox

### ISSUE THREAD

**Issue by mrneilypops** [dutchcoders/transfer.sh#188]
Hi,
I am trying to add transfer.sh to a menu entry and open firefox when the upload completes at the correct page.

scrot -d 5 ~/screenshots/screenshot.png && curl --upload-file ~/screenshots/screenshot.png https://transfer.sh/screenshot.png

Any help most welcome.

**Comment by aspacca** [comment]
@mrneilypops please, give some more context

**Comment by aspacca** [comment]
for example: you can do this on macos:
`curl --upload-file hello.txt https://transfer.sh/ | xargs open`

**Comment by mrneilypops** [comment]
Thank you.
This works for me on linux.
scrot -d 5 ~/screenshots/screenshot.png && curl --upload-file ~/screenshots/screenshot.png https://transfer.sh/ | xargs firefox
