### ISSUE TITLE
Could not save metadata

### ISSUE THREAD

**Issue by valord577** [dutchcoders/transfer.sh#191]
![image](https://user-images.githubusercontent.com/30427460/51481728-8054fd00-1dcf-11e9-8502-add3250656e4.png)

![image](https://user-images.githubusercontent.com/30427460/51482002-3a4c6900-1dd0-11e9-8c66-c10585ffadce.png)

Location: Hangzhou, China
OS: Darwin v10.13.6

Excuse me! Was the problem caused by the high network delay?

**Comment by mckaygerhard** [comment]
ummm seeems related to the big firewall of china?

**Comment by mckaygerhard** [comment]
ummm myabe related to #190 see htere

**Comment by mckaygerhard** [comment]
in some networks/dns this are happened.. so maybe unrelated to trasnfersh

**Comment by valord577** [comment]
@mckaygerhard Emmm, thanks very much. 
The big firewall is a very annoying thing. 
I will try to modify DNS and other ways.  :-)
