### ISSUE TITLE
Automatic deletion?

### ISSUE THREAD

**Issue by JustAnotherArchivist** [dutchcoders/transfer.sh#212]
The web frontend includes a [hardcoded](https://github.com/dutchcoders/transfer.sh-web/blob/e7d393abbb072dc15fca8581c090fc3e8a936324/src/index.html#L100) message that "files [are] stored for 14 days", implying an automatic deletion 2 weeks after the upload. But is that actually the case? I know that https://transfer.sh/ did (when you were still running it) and still does delete files after a while, but I was unable to find any code for this. Did I just miss it, or is/was that something external like a cronjob running `find` with `-mmin` and `-delete`? If it is the former, how could the deletion be adjusted to keep files for a longer time?

**Comment by aspacca** [comment]
@JustAnotherArchivist there's no code related to it. I never managed https://transfer.sh so I don't know what was the case here and what's going on now. I will remove the message in the codebase of the frontend

**Comment by aspacca** [comment]
@JustAnotherArchivist for current codebase there's a `X-Url-Delete` delete header with an URL you can send a `DELETE` request to to delete the file
