### ISSUE TITLE
Missing percent-encoding of hashes (#) in returned URL

### ISSUE THREAD

**Issue by JustAnotherArchivist** [dutchcoders/transfer.sh#213]
When uploading a file whose name contains a hash (`#`), the returned URL also contains that symbol literally. This means that the returned URL will 404 although the upload itself was successful. The hash needs to be percent-encoded as `%23` instead so that clients don't treat the rest of the URL as a fragment.

    > curl --upload-file test#test https://transfer.sh/
    https://transfer.sh/150xUz/test#test

should produce

    https://transfer.sh/150xUz/test%23test

This happens regardless of whether you use a filename containing a hash with `--upload-file` or specify the filename in the URL like `https://transfer.sh/foo%23bar` (where the hash of course needs to be encoded as well so that curl doesn't strip it away).

**Comment by aspacca** [comment]
@JustAnotherArchivist it was fixed month ago on codebase. I have no control on version deployed on `https://tranfer.sh`

**Comment by JustAnotherArchivist** [comment]
Oh, I see, didn't see that. We're running our own instance, but I guess the code isn't up-to-date then. Thanks!
