### ISSUE TITLE
Percent-encoding in filenames not handled correctly

### ISSUE THREAD

**Issue by JustAnotherArchivist** [dutchcoders/transfer.sh#215]
Percent-encoding in filenames is not handled correctly:

    > echo foo > test%C3%A4test
    > curl --upload-file test%C3%A4test https://{redacted}/;echo
    https://{redacted}/LN3I1/test%C3%A4test

Loading that URL produces a 404 because the file was actually uploaded as `https://{redacted}/LN3l1/test%25C3%25A4test` instead, i.e. with the per cent symbols encoded as `%25`. That's probably the correct way to handle such uploads, but the output of the PUT request should also reflect it.

**Comment by aspacca** [comment]
you're right @JustAnotherArchivist : the current solution was a little clumsy. I fixed with a more straightforward one in #216 , can you give a try?

**Comment by JustAnotherArchivist** [comment]
Thanks, I can confirm that #216 fixes this.
