### ISSUE TITLE
Update Dockerfile from n8225/transfer.sh

### ISSUE THREAD

**Issue by aspacca** [dutchcoders/transfer.sh#219]
@n8225, you edited Dockerfile to build static and use scratch image for a smaller container

I would like to include the change in the official repository, but it would be nice if you open the PR for it

**Comment by dopessoa** [comment]
As @n8225 hasn't answered in quite a while I've made some improvements to the Dockerfile based on his changes, I've sent a PR with the new Dockerfile.

**Comment by aspacca** [comment]
fixed by #231
