### ISSUE TITLE
Add raw link to the file

### ISSUE THREAD

**Issue by epeli** [dutchcoders/transfer.sh#22]
transfer.sh seems to do some kind of user agent sniffing and it displays the files in a HTML wrapper in the browser. Which is fine, but it should also display a raw link to the file which does not ever add the wrapper because now it is impossible to view images in their full size or use JSON-formatting extensions to view json files in browser.

**Comment by nl5887** [comment]
When we had links to the raw url, the service was abused by phishers which included the raw images and scripts within their phishing sites. We've chosen for a solution that when the referer is transfer.sh the raw file will be shown. I'll look into a solution.
