### ISSUE TITLE
Transfer.sh is currently down

### ISSUE THREAD

**Issue by linuxct** [dutchcoders/transfer.sh#220]
Title self explanatory. Seems to be an outage that's causing a service degradation from Spain, and Germany as far as I can tell.

**Comment by aspacca** [comment]
this repo has no connection with the http://transfer.sh hosted service and there's nothing I could do about it

**Comment by aspacca** [comment]
also: I've just tested and it works properly from germany

**Comment by linuxct** [comment]
The repo may not be intrinsically connected to https://transfer.sh, but it's being hosted by DutchCoders, who also are the owners of the repo. Correct me if I'm wrong. 

Still getting ERR_CONNECTION_TIMED_OUT from our Spain and Germany front servers. Will wait to see if  we get escalated any other network issue or if it's just this specific case.

**Comment by aspacca** [comment]
the repo is hosted on github and I'm the maintainer. I never had any control on https://transfer.sh that was maintained and hosted by dutchcoders but it is now hosted by storj with totally independence (as far as I know they don't use the service from the repo code baseline)
I've no connection with storj and I've never been in contact with them

**Comment by linuxct** [comment]
Thank you, I've emailed storj to notify them.
