### ISSUE TITLE
Options to only allow specific IP address to upload

### ISSUE THREAD

**Issue by misaka00251** [dutchcoders/transfer.sh#223]
Or something like whitelist / blacklist feature? Because when it comes to self-hosted, abuse is a big problem.

**Comment by aspacca** [comment]
there are `--http-auth-user` and `--http-auth-pass` that will add http basic auth for a single account only on upload, can this solve your issue?

a whitelist/blacklist feature could be useful anyway

**Comment by misaka00251** [comment]
Well, I managed a private GitLab instance (for me and my friends) and have some shared GitLab runners (runners are on two different machines), and I only want these shared machines to use this service. Clearly here `--http-auth-user` and `--http-auth-pass` isn't a perfect solution, since it might be leaked...

**Comment by aspacca** [comment]
addressed in #224, please @misaka00251 test on that branch

I also switched to go module there

**Comment by misaka00251** [comment]
Tested and it works.
Issues:
Already set a list of IPs like `--ip-whitelist="1.1.1.1, 2.2.2.2"`, but only `1.1.1.1` can access.

**Comment by aspacca** [comment]
@misaka00251 there's no sanitization of the input: so ` 2.2.2.2` will fail to be parsed because of the space in the beginning

**Comment by aspacca** [comment]
fixed
