### ISSUE TITLE
Get a status page to announce downtime

### ISSUE THREAD

**Issue by akaleeroy** [dutchcoders/transfer.sh#226]
Site is down, and I'm about to get a _Why don't you just use <normie mainstream inferior solution like WeTransfer/Google/Dropbox>_ from the person I was trying to send files to.

If possible get a status page to announce down time.

**Comment by aspacca** [comment]
Disclaimer

This project repository has no relation with the service at https://transfer.sh that's managed by https://storj.io. So far we cannot address any issue related to the service at https://transfer.sh.
