### ISSUE TITLE
Append Max-Downloads and Max-Days on response headers

### ISSUE THREAD

**Issue by dopessoa** [dutchcoders/transfer.sh#229]
Are there any plans to add Max-Downloads and Max-Days current values as response headers on GET and HEAD requests?

I guess this is slightly related to #178.

**Comment by aspacca** [comment]
now there is, I don't know when I'll have time to do it anyway

**Comment by aspacca** [comment]
but I guess the headers should be Remaining-Downloads and Remaining-Days to be useful

**Comment by dopessoa** [comment]
OK, I've been really busy lately, but I'll send a PR in the next few days.

**Comment by aspacca** [comment]
really busy here as well, if you plan to send a PR for this I will wait for it

**Comment by dopessoa** [comment]
Sent a PR, please review when you got the time.

Found what I think is an issue while developing this, I'll open a new issue to document my finding.
