### ISSUE TITLE
configurable default metadata

### ISSUE THREAD

**Issue by grinapo** [dutchcoders/transfer.sh#240]
Is there a reason that the default metadata (10 years and millions of downloads) is not configurable? 

Also related: there seem to be no way to administratively set the maximum amount of downloads and expiration time, which may possibly be different from above.

**Comment by aspacca** [comment]
I don't know about the reason, since the choice was made before I joined the project: it could be something "big enough" to be like not set.
for me if there're no header for expiration set there should be no limit, I will look in properly do this without relying on "big enough" values

**Comment by aspacca** [comment]
@grinapo fixed in #246
