### ISSUE TITLE
Doesn't work on MacOS X 10.6

### ISSUE THREAD

**Issue by pixelwitches** [dutchcoders/transfer.sh#25]
Process:         launchd [11727]
Path:            /Users/melody/Downloads/transfer.sh.app/Contents/MacOS/applet
Identifier:      com.apple.ScriptEditor.id.transfer-sh
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [124]

Date/Time:       2015-03-30 01:01:51.863 +1100
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          69981219 sec
Crashes Since Last Report:           836
Per-App Crashes Since Last Report:   4
Anonymous UUID:                      FC5CA901-E8AF-4044-8E64-7AFB441F5ECA

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8

Binary images description not available

Model: iMac8,1, BootROM IM81.00C1.B00, 2 processors, Intel Core 2 Duo, 2.4 GHz, 4 GB, SMC 1.29f1
Graphics: ATI Radeon HD 2400 XT, ATI Radeon HD 2400, PCIe, 128 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8C), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Ethernet Adaptor (en3), Ethernet, en3
Serial ATA Device: Hitachi HDP725025GLA380, 232.89 GB
Parallel ATA Device: MATSHITADVD-R   UJ-875
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8502, 0xfd400000 / 3
USB Device: USB 2.0 Hub [MTT], 0x1a40  (TERMINUS TECHNOLOGY INC.), 0x0201, 0xfd100000 / 2
USB Device: nanoKONTROL2, 0x0944  (KORG, Inc.), 0x0117, 0xfd120000 / 7
USB Device: USB to Serial-ATA bridge, 0x059b  (Iomega Corporation), 0x0577, 0xfd170000 / 6
USB Device: iMic USB audio system, 0x077d, 0x07af, 0xfd140000 / 5
USB Device: QX61, 0x13b2, 0x0077, 0xfd150000 / 4
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0x5d100000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x1a100000 / 2
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x820f, 0x1a110000 / 4
USB Device: 2.4G Keyboard Mouse, 0x062a  (ProVision Technology, Inc.), 0x4101, 0x3a200000 / 2

**Comment by nl5887** [comment]
What app is this? I think you've created this issue in the wrong repository.
