### ISSUE TITLE
Reverse proxy: support X-Forwarded-Port, or allow some sort of --proxy-port

### ISSUE THREAD

**Issue by zmwangx** [dutchcoders/transfer.sh#252]
I'm hosting transfer.sh on a certain server where unfortunately port 443 is off limits, so I'm exposing the service on port 8443 instead. I'm using nginx as a reverse proxy in front of the transfer.sh server, where the configuration includes

```nginx
        proxy_set_header   Host                 $host;
        # ...
        proxy_set_header   X-Forwarded-Port     8443;
```

The server doesn't support the `X-Forwarded-Port` header though, so unfortunately all URLs I get don't have the port attached. Is it possible to add support for the header, or maybe add some server option so that a non-default port could be used? Thanks.

**Comment by aspacca** [comment]
@zmwangx, putting the proxy port in the `Host` header is enough:
```nginx
        proxy_set_header   Host                 $host:8443;
```

**Comment by zmwangx** [comment]
Didn't think of that... Thanks.
