### ISSUE TITLE
Question: Passing an argument to docker to set the return URL

### ISSUE THREAD

**Issue by sean-perryman** [dutchcoders/transfer.sh#263]
Apologies if this is the wrong place to post this.

As I am starting to need to pass around more sensitive information, and am learning Docker, I decided to try and roll my own copy of transfer.sh. It is working great with Nginx as the SSL front end, but I cannot seem to figure out how to get the transfer.sh server to recognize the external URL. Is there a setting or something I can set to perform this task? I am just using the Docker command you have listed on the Github page, but perhaps its something I can do in a Dockerfile? 

Current output: 

```
$ transfer testfile
######################################################################## 100.0%
http://127.0.0.1:8080/123jaT/testfile
```

Instead of the desired:

```
$ transfer testfile
######################################################################## 100.0%
https://external.url/123jaT/testfile
```

**Comment by aspacca** [comment]
@sean-perryman you mentioned Nginx, that I presume you use as proxy to the transfer service in the docker container.
In this case you have to add in the Nginx configuration the following:
```
proxy_set_header   Host                 $host;
```
