### ISSUE TITLE
runtime error: index out of range when uploading zip

### ISSUE THREAD

**Issue by camielverdult** [dutchcoders/transfer.sh#264]
Hello,

I tried to upload a 3,61GB ZIP to transfer.sh today, it gave me "Error (500) during upload of file data.zip". When I "downloaded", the ZIP again, the transfersh.zip.txt had only one line: `runtime error: index out of range`.

**Comment by aspacca** [comment]
hello @camielverdult, sorry we have no control on the version of the service hosted at transfer.sh
if you are able to reproduce the issue with the current master feel free to reopen the ticket
