### ISSUE TITLE
Listening only on IPV6 after building

### ISSUE THREAD

**Issue by Auroch** [dutchcoders/transfer.sh#27]
After building on Debian Jessie, the transfersh-server only listen on ipv6 and on my OHV VPS, I can't disable IPV6.
Is there something I missed (some parameters on the command line) or do you think it's related to the #1 response from google at this other issue ?
https://code.google.com/p/go/issues/detail?id=5197

**Comment by nl5887** [comment]
What I'm reading at https://groups.google.com/forum/#!msg/golang-nuts/F5HE7Eqb6iM/q_um2VqT5vAJ is that the ipv4 packets are being received through the ipv6 address. Did you tested if it is able to receive data through the ipv4 address?

```on linux, by default, net.ipv6.bindv6only is 0, so ipv4 packets could also be received from
ipv6 sockets with ipv4-mapped ipv6 address. thus you only need to listen on tcp6 socket
and we can support both ipv4 and ipv6.```

**Comment by Auroch** [comment]
Hi, thanx for the reply !
But i'm not really sure to understand ... because (for me) nothing really come on this machine throught IPV6 (I think). Its seem to me (but maybe I'm wrong) that I can only arrive on it throught IPV4 traffic and when I test with a netstat -lntp the port listening is only on IPV6.
Sorry if I'm completely wrong, but I don't know how I can check if the building works.

my transfersh-server : 
> ./transfersh-server -provider=local --port 8080 --temp=/tmp/ --basedir=/tmp/
> 2015/05/07 13:22:36 Transfer.sh server started. :
> listening on port: 8080
> using temp folder: /tmp/
> using storage provider: local
> 2015/05/07 13:22:36 ---------------------------'''

my test : 
> curl -g -6 --upload-file test.txt http://[::1]:8080/test.txt

return:
> curl: (7) Couldn't connect to server

**Comment by Auroch** [comment]
Sorry, in fact, that work as you said but only if I test with local IP and not localhost ^^
This is OK
>curl --upload-file ./test.txt http://127.0.0.1:8080/test.txt

This NOT ok
>curl --upload-file ./test.txt http://localhost:8080/test.txt

Do you think it's normal the reply is in https ?
>https://127.0.0.1/KIFsa/test.txt

**Comment by fredlubrano** [comment]
Hi, 

I have the same problem "transfer server" listen on IPV6 only (Ubuntu 14.04).
The configuration of the IPv6 is disabled on the network interface 
systcl.conf
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1

test 

# ./transfersh-server -provider=local --port 8080 --temp=/tmp/ --basedir=/tmp/
2015/12/05 15:04:10 Transfer.sh server started. :
listening on port: 8080
using temp folder: /tmp/
using storage provider: local
2015/12/05 15:04:10 ---------------------------


# ssldump -nni eth0 -Aed port 8080

New TCP connection #1: 88.XXX.XXX.XXX (49133) <-> 10.1.4.150(8080)
1449327978.9676 (0.0145)  C>S
---------------------------------------------------------------
PUT /charles-proxy-3.11.3b4.dmg HTTP/1.1
Host: scal.xxxx.net:8080
User-Agent: curl/7.43.0
Accept: */*
Content-Length: 57032570
Expect: 100-continue

---------------------------------------------------------------

1449327978.9680 (0.0003)  S>C
---------------------------------------------------------------
HTTP/1.1 301 Moved Permanently
Location: https://transfer.sh/charles-proxy-3.11.3b4.dmg
Server: Transfer.sh HTTP Server 1.0
X-Made-With: <3 by DutchCoders
X-Served-By: Proudly served by DutchCoders
Date: Sat, 05 Dec 2015 15:06:18 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

---------------------------------------------------------------

1    1449327978.9818 (0.0137)  C>S  TCP FIN
1    1449327978.9819 (0.0001)  S>C  TCP FIN

# lsof -ni
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
@xnbd-cli   863 root    3u  IPv4    232      0t0  TCP 10.1.4.150:40418->10.1.4.155:4608 (ESTABLISHED)
dhclient   1794 root    6u  IPv4    983      0t0  UDP *:bootpc
dhclient   1794 root   20u  IPv4   7203      0t0  UDP *:59014
dhclient   1794 root   21u  IPv6   7204      0t0  UDP *:60074
sshd       1900 root    3r  IPv4   2818      0t0  TCP *:ssh (LISTEN)
sshd       1900 root    4u  IPv6   2820      0t0  TCP *:ssh (LISTEN)
sshd       2003 root    3r  IPv4   8207      0t0  TCP 10.1.4.150:ssh->88.XXX.XXX.XXX:59909 (ESTABLISHED)
ntpd       2263  ntp   16u  IPv4   6882      0t0  UDP *:ntp
ntpd       2263  ntp   17u  IPv6   6883      0t0  UDP *:ntp
ntpd       2263  ntp   18u  IPv4   6889      0t0  UDP 127.0.0.1:ntp
ntpd       2263  ntp   19u  IPv4   6890      0t0  UDP 10.1.4.150:ntp
sshd      12300 root    3r  IPv4  17852      0t0  TCP 10.1.4.150:ssh->88.XXX.XXX.XXX:36092 (ESTABLISHED)
transfers 12661 root    3u  IPv6  19949      0t0  TCP *:http-alt (LISTEN) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 

# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:07:cb:03:30:9d
          inet addr:10.1.4.150  Bcast:10.1.5.255  Mask:255.255.254.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:192153 errors:0 dropped:0 overruns:0 frame:0
          TX packets:133889 errors:0 dropped:16 overruns:0 carrier:0
          collisions:0 txqueuelen:532
          RX bytes:171368714 (171.3 MB)  TX bytes:944118436 (944.1 MB)
          Interrupt:8

Thanks for the help

Best regards,

fred

**Comment by aksswami** [comment]
As @Auroch described, I am also facing same problem after building on OSX with docker. Not able to access it via `localhost` but working fine with `127.0.0.1`. If I try from another machine on same network with network IP, then also it is not working.

**Comment by aspacca** [comment]
@aksswami , @fredlubrano , @Auroch , still relevant?
