### ISSUE TITLE
Curl could not save metadata

### ISSUE THREAD

**Issue by Xhendos** [dutchcoders/transfer.sh#271]
Using `curl 7.58` on a Debian flavor and `curl 7.20` on Minix3.1.8 it is not possible to upload a file to transfer.sh
I use `curl -k --upload-file ./file-name https://transfer.sh/file-name` and curl returns `Could not save metadata`

Is anyone else suffering the same issue?

EDIT: I read the disclaimer too late. Problems with the webhost should not be issues here.

**Comment by aspacca** [comment]
@Xhendos the service hosted at https://transfer.sh is separated and not maintened by this repo
