### ISSUE TITLE
Simply not working for me

### ISSUE THREAD

**Issue by JayBrown** [dutchcoders/transfer.sh#272]
I'm using both the following options in a shell script:

```
curl -k --connect-timeout 30 -H "Max-Days: 7" --upload-file "$filepath" "https://transfer.sh/$filename"
curl -k --connect-timeout 30 -H "Max-Downloads: 1" -H "Max-Days: 7" --upload-file "$filepath" "https://transfer.sh/$filename" 2>/dev/null
```

…and it never returns a URL. Often it doesn't even care about the 30 seconds timeout argument and simply runs forever. Also tried it directly/manually in Terminal, no change.

What gives?

**Comment by aspacca** [comment]
@JayBrown the repo is not related to the service hosted on https://transfer.sh
