### ISSUE TITLE
Could not save metadata

### ISSUE THREAD

**Issue by andreasonny83** [dutchcoders/transfer.sh#277]
```sh
$ transfer README.md                                                                                                                                                 
################## 100.0%
Could not save metadata
```

I understand that the service hosted at https://transfer.sh is separated and not maintained by this repo, however, I don't see another way for reporting this problem directly to @nl5887 .
I would just like to know if the service is still online and alive.
Thanks.

**Comment by sxiii** [comment]
Same for me both from CLI and from browser uploader...

**Comment by aspacca** [comment]
@andreasonny83 you may want to ping @stefanbenten

**Comment by morrigan** [comment]
This issue still persists.

**Comment by andreasonny83** [comment]
If you are interested, I have just recently built something similar called transfer-now on: https://www.npmjs.com/package/transfer-now

**Comment by aspacca** [comment]
@andreasonny83 interesting. Where are the file hosted? Is the packaged a client only or a server, like transer-sh? I don't find the source code online

**Comment by stefanbenten** [comment]
I just took a look at the host and fixed the issue. Every now and then it rans out of memory.

**Comment by andreasonny83** [comment]
@aspacca the files are stored on aws s3. the cli is just the client side, the server is actually running on the aws side inside Lambda. The source code is not online. I'm planning to scale that project up and have a proper service with a pro plan eventually

**Comment by arcooke** [comment]
> I just took a look at the host and fixed the issue. Every now and then it rans out of memory.

The issue has returned

![image](https://user-images.githubusercontent.com/6278400/72209771-c4755d80-3477-11ea-9e99-643aea0aff17.png)

**Comment by TheLastProject** [comment]
Well, reading through this treat:
ping @stefanbenten

**Comment by stefanbenten** [comment]
We are in the process of migrating the tool to our network with PR #266 .
Waiting for review and test from @aspacca .

**Comment by stefanbenten** [comment]
I checked the current host and it seems to operate fine, besides being very busy.

**Comment by blightwing** [comment]
The issue has returned.

**Comment by gonubana** [comment]
For anyone encountering this problem, oshi.at may be their solution. Just saying...

**Comment by 2spirit** [comment]
same issue today...

**Comment by Whoffie** [comment]
It has returned on command line uploads for me

**Comment by michaeleisel** [comment]
I'm having the same issue
