### ISSUE TITLE
support Range request from HTTP Header

### ISSUE THREAD

**Issue by johnko** [dutchcoders/transfer.sh#28]
Hi,

If you want to support Range requests, the easy way is you need something like

```
http.ServeContent(w, r, filename, modTime, seeker)
```

in your `getHandler` instead of the io.Copy.

This will allow seeking for media files.

**Comment by johnko** [comment]
example in my fork https://github.com/johnko/wtfc/blob/master/transfersh-server/handlers.go#L612-631

**Comment by aspacca** [comment]
@johnko `storage.Seeker` seems to be suitable only for local storage
