### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by sgorki** [dutchcoders/transfer.sh#282]
Please help me to install this source to Heroku and integrate with Google Drive

**Comment by aspacca** [comment]
@sgorki did you solve the problem?
for Google Drive integration you can check https://github.com/dutchcoders/transfer.sh/issues/273
I cannot help with Heroku

**Comment by sgorki** [comment]
> @sgorki did you solve the problem?
> for Google Drive integration you can check #273
> I cannot help with Heroku

I just want to deploy to Heroku
