### ISSUE TITLE
Open link, after a file is uploaded

### ISSUE THREAD

**Issue by jtagcat** [dutchcoders/transfer.sh#285]
I'm used to copying the link with Ctrl+L Ctrl+C (from the URL bar), I have to click it every time, or right click and copy this URL.
I know it has conflicts with the zipping options, any ideas?

**Comment by aspacca** [comment]
are you referring to the service hosted at https://transfer.sh?

**Comment by jtagcat** [comment]
Yes, but I'm also using my self-hosted instance of it.

**Comment by aspacca** [comment]
@jtagcat the version hostend on https://transfer.sh and the version in the repo if you self-host are different, so please give more details.
1. what version (/git tag) of the service are you self-hosting?
2. what are the steps to reproduce the issue?

**Comment by jtagcat** [comment]
1. No idea where to check that. `dutchcoders/transfer.sh:latest` on docker.
2. the feature does not exist

**Comment by aspacca** [comment]
@jtagcat your request is not feasable: to allow you to `Ctrl+L Ctrl+C` the page should redirect to the url of the file uploaded, but since you can upload multiple files from the frontend and you'll have multiple urls to redirect to
