### ISSUE TITLE
Can't configure nginx reverse proxy to transfer.sh

### ISSUE THREAD

**Issue by HamedSepehr** [dutchcoders/transfer.sh#287]
I have transfer.sh running on my vps using docker on port 8081 and this is how I ran it and it works fine:

`docker run -d --publish 8081:8080 -v /etc/transfer/tmp:/tmp --name=transfer-test dutchcoders/transfer.sh:latest --provider local --basedir /tmp/`

For webserver I'm using [linuxserver/letsencrypt](https://hub.docker.com/r/linuxserver/letsencrypt) which is based on nginx. I wan to proxy `domain.com/transfer` to transfer.sh. This is the configuration I'm using:

> location /transfer {
>     client_max_body_size 1M;
>     proxy_pass http://vps_ip:8081;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade; # allow websockets
>     proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
>     proxy_set_header        Host $host;
>     proxy_set_header        X-Real-IP $remote_addr;
>     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header        X-Forwarded-Proto $scheme;
> }

And this is the result:
[![transfer-sh.jpg](https://i.postimg.cc/vmTKWSRr/transfer-sh.jpg)](https://postimg.cc/R3rGmdZh)

I have no idea what's wrong...

**Comment by vyachkonovalov** [comment]
Try to add slashes, one for location `location /transfer/`, another for proxy_pass `proxy_pass http://vps_ip:8081/;`
```
Also remove `Upgrade` header.

**Comment by vyachkonovalov** [comment]
`--listener`'s value has a colon before port number. I spent half an hour trying to figure out what's wrong, because transfer.sh doesn't show any error in case you forgot a colon😟

**Comment by HamedSepehr** [comment]
I did all of them and now it works without any problem. thanks

**Comment by HamedSepehr** [comment]
> Try to add trailing slashes, one for location `location /transfer/`, another for proxy_pass `proxy_pass http://vps_ip:8081/;`
> Also remove `Upgrade` header.
> Or you could use `transfersh --proxy-path transfer` (path prefix when service is run behind a proxy).

I did all of them and now it works without any problem, thanks.

**Comment by aspacca** [comment]
thanks @vyachkonovalov for the support
