### ISSUE TITLE
Download links aren't resumable

### ISSUE THREAD

**Issue by HamedSepehr** [dutchcoders/transfer.sh#289]
How can I make download links resumable so I can pause download and resume download later?

**Comment by aspacca** [comment]
if the request for the resumed download has `Range` header it should work out of the box, can you please test?

**Comment by HamedSepehr** [comment]
I don't how I should test that...
So far I have tested `aria2c -c`, `wget -c` and IDM and none of them was able to resume download.

**Comment by aspacca** [comment]
I can confirm that `wget -c` works properly

**Comment by aspacca** [comment]
@HamedSepehr I assume that you are talking about your own hosted service, not the one on https://transfer.sh

**Comment by HamedSepehr** [comment]
My bad... Yes I'm talking about my own hosted service which is behind nginx reverse proxy.

**Comment by aspacca** [comment]
@HamedSepehr did it work?

**Comment by HamedSepehr** [comment]
> @HamedSepehr did it work?

I couldn't make transfer.sh links resumable, instead I changed my configuration in a way that transfer.sh files are accessible through nginx and now I'm downloading files from nginx.
