### ISSUE TITLE
Damn, the yellow thing covers download button on mobile

### ISSUE THREAD

**Issue by blueberry6401** [dutchcoders/transfer.sh#292]
Here it is.
![90562359_232041527987768_7463646531782967296_n](https://user-images.githubusercontent.com/7337535/77510789-243dab00-6ea2-11ea-82cb-d46d9e397416.jpg)

**Comment by aspacca** [comment]
This project repository has no relation with the service at https://transfer.sh that's managed by https://storj.io. So far we cannot address any issue related to the service at https://transfer.sh.
