### ISSUE TITLE
Settings via ENV vars

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [dutchcoders/transfer.sh#301]
Hi,

would it be possible to enable the settings (like provider etc.) via environment variables?
there are a lot of gui implementations for docker (e.g. in synology nas or plesk) that only allow the setting of env vars and not adding something to the run command.

thanks!
cheers
Tobias

**Comment by aspacca** [comment]
hello @tofuSCHNITZEL 

that sould be pretty easy and some of the settings can be already provided by environment variables (see https://github.com/dutchcoders/transfer.sh/blob/master/cmd/cmd.go#L103)

I'm not sure when I'll have time to do it so you're welcome if you want to open a PR for it.

**Comment by tofuSCHNITZEL** [comment]
its as easy as adding the "EnvVar" to all the flags?
if so... done: https://github.com/dutchcoders/transfer.sh/pull/304

**Comment by aspacca** [comment]
merged to master, thanks @tofuSCHNITZEL
