### ISSUE TITLE
Custom Web Interface???

### ISSUE THREAD

**Issue by oriolrius** [dutchcoders/transfer.sh#303]
Hi guys, first of thanks for your works it's really useful. I have your app running open at x.joor.net.

BTW, my question is about the parameter 'web-path' because I don't know what do I have to put at that path for having my front end page.

Thanks in advance for your support.

Oriol

**Comment by aspacca** [comment]
hello @oriolrius , thanks for you appreciation

regarding the custom front-end you are right: I should document how to setup

I will try to help you throught reference to the code, in the meanwhile.

The frontend exepect to have some files with fixed names processed as go templates.
The variable used in the templates are the following:
https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L177-L187
These will be used in the template files as `{{ .ContentType }}` for example.

You can find the list of filenames for the preview page in these lines:
https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L123-L158

and for the index page here: https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L231-L236 (both text and htlm)

You could checkout and build https://github.com/dutchcoders/transfer.sh-web to see the template samples from the embedded frontend.

Please let me know if it helped

**Comment by aspacca** [comment]
@oriolrius did you manage to use a custom frontend?

**Comment by oriolrius** [comment]
Thanks @aspacca for helping me, finally I had some hours for trying it. I spend more than 2h trying to understand how grunt and bower works but finally, I had the chance to customize the UI.

Sadly, I spent about 3' to "compile" everything every time I want to check any change because I have to wait "grunt build". I suspect I miss something about how to do it.

**Comment by mckaygerhard** [comment]
maybe you must paste here exact comands to property helps (also make more detailed documentation.. i can make it) @oriolrius

**Comment by aspacca** [comment]
@oriolrius happy to help. from grunt you should be able to use the`serve` command to  wach live changes to the code, btw
