### ISSUE TITLE
Cannot use behind proxy running on a different port

### ISSUE THREAD

**Issue by cheeseandcereal** [dutchcoders/transfer.sh#306]
Right now, the `--proxy-path` parameter allows you to run this program behind a web proxy which changes the path of a request, however it does not have a way to take into account the fact that a proxy may also be running on a different port.

For example, if I run this on port 1234 with a web proxy pointing to it at path /ex which is listening on port 80, uploading a file results in the response url: `http://localhost:1234/ex/<token>/<file>`

This is incorrect, as to go through the proxy, the port must be 80

An option needs to be added (something like `--proxy-port`) which allows you to specify the port number of a proxy fronting this service.

**Comment by aspacca** [comment]
@cheeseandcereal this can be achieved setting the `Host` header with the port as well
see https://github.com/dutchcoders/transfer.sh/issues/252 for a solution on nginx

**Comment by cheeseandcereal** [comment]
That's fine for an HTTP proxy which supports modifying requests, but not for something lower level like a raw TCP proxy, or simple routing/firewall rules which are forwarding between different ports

Would you accept a PR if I implemented `--proxy-port` ?

**Comment by aspacca** [comment]
oki
