### ISSUE TITLE
Uploading from Travis CI failed

### ISSUE THREAD

**Issue by Symbian9** [dutchcoders/transfer.sh#312]
- https://travis-ci.org/github/Symbian9/Astree/builds/692934176
  - https://api.travis-ci.org/v3/job/692934177/log.txt

```
...
$ curl --upload-file Astree-nightly.zip https://transfer.sh/Astree-nightly.zip
Could not save metadata
Could not save metadata
Could not save metadata
...
```

**Comment by aspacca** [comment]
https://github.com/dutchcoders/transfer.sh#disclaimer

This project repository has no relation with the service at https://transfer.sh that's managed by https://storj.io. So far we cannot address any issue related to the service at https://transfer.sh.
