### ISSUE TITLE
Possible to activate CORS?

### ISSUE THREAD

**Issue by antgonza** [dutchcoders/transfer.sh#319]
Thank you for https://transfer.sh/, it seems really helpful and it's great to read about the partnering with Storj Labs.

Anyway, I'm trying to link one of my files with another application via CORS but it seems like it's not enabled in the server; [here](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Ftransfer.sh%2Fv2rm4%2Fempress-tree.qzv&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) you can test that connectivity. 

Would it be possible to activate it?

BTW, in case it helps [here](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fview.qiime2.org%2F%3Fsrc%3Dhttps%253A%252F%252Fdocs.qiime2.org%252F2020.6%252Fdata%252Ftutorials%252Fmoving-pictures%252Fcore-metrics-results%252Funweighted_unifrac_emperor.qzv&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) is an example with CORS.

**Comment by cheeseandcereal** [comment]
--cors-domains is an option which lets you specify the domains you want to allow with CORS:
https://github.com/dutchcoders/transfer.sh#usage-1
