### ISSUE TITLE
[Question] Files with same token can't be easily zipped together?

### ISSUE THREAD

**Issue by ShadowKyogre** [dutchcoders/transfer.sh#32]
Hi transfer.sh devs! I love the service you've provided, but I have one little question.

I notice that when I upload files over curl in batches, they'll have the same token. EG:

```
https://transfer.sh/IMTKN/file.name
https://transfer.sh/IMTKN/file2.name
```

But when I upload via the website, I get this:

```
https://transfer.sh/IMTKN/file.name
https://transfer.sh/IMTKN2/file2.name
```

I know how to write the url to bundle files under a single zip or .tar.gz, but is there a reason why files underneath the same token can't simply be referred to as `https://transfer.sh/IMTKN.zip` for a shorter URL? Just curious.

**Comment by aspacca** [comment]
@ShadowKyogre you can actually do something like: `curl -v "https://transfer.sh/(12pWqz/hello.txt,ZgZGV/hello.txt).tar.gz" -o test.tgz`
