### ISSUE TITLE
Is transfer.sh still alive?

### ISSUE THREAD

**Issue by probonopd** [dutchcoders/transfer.sh#321]
Is transfer.sh still alive?

**Comment by mckaygerhard** [comment]
yes.. why you asking? is working if you compiled it! ans deploy in your host!

**Comment by probonopd** [comment]
Sorry if I was unclear, I am referring to the public instance hosted at https://transfer.sh - it seems to be really, really slow these days.

**Comment by cheeseandcereal** [comment]
There is a disclaimer you should read at the _very top_ of the readme

https://github.com/dutchcoders/transfer.sh#disclaimer

**Comment by ChristianVaughn** [comment]
They should edit the about section of the project then because it directly links to https://transfer.sh. somewhat misleading since the about section on github is seen before the readme.

**Comment by aspacca** [comment]
done @ChristianVaughn

**Comment by probonopd** [comment]
Thanks. What is misleading is that https://transfer.sh links directly here.
