### ISSUE TITLE
How to remove time & size limit on self-hosted deployment?

### ISSUE THREAD

**Issue by UmutAlihan** [dutchcoders/transfer.sh#323]

**Comment by aspacca** [comment]
what time and size limit @UmutAlihan ?

could you give more details?

**Comment by UmutAlihan** [comment]
as the homepage mentions,

- 10GB max size
- 14 days max storage duration

Does these limitations exist on self-hosted deployment?

I couldn't see anything related in the code. However I don't know Golang.  I can only read the overall code without syntax knowledge. Thus it is likely that I miss sth..

**Comment by aspacca** [comment]
there're no such limitation in the code

**Comment by UmutAlihan** [comment]
thank youu!
