### ISSUE TITLE
Does this code support Google Teamdrives?

### ISSUE THREAD

**Issue by telegrambotdev** [dutchcoders/transfer.sh#325]
Does this code supports,google shared drives as file hoster ?

**Comment by aspacca** [comment]
hi @telegrambotdev , I haven't ever tested: I would expect for it to work if you have the right permission.
fastest way to find out is just to try it

**Comment by telegrambotdev** [comment]
> hi @telegrambotdev , I haven't ever tested: I would expect for it to work if you have the right permission.
> fastest way to find out is just to try it

but there is no place to mention shared drive id.Thats were i am confused

**Comment by aspacca** [comment]
@telegrambotdev got it: I don't know how shared drive works. are they not "mounte" on a folder in your drive? in this case just setting the path to that folder could be fine
If you send me some documentations (a link is enough) I could try to add the support

**Comment by telegrambotdev** [comment]
> @telegrambotdev got it: I don't know how shared drive works. are they not "mounte" on a folder in your drive? in this case just setting the path to that folder could be fine
> If you send me some documentations (a link is enough) I could try to add the support

you can use rclone for shared drive support.Thats the most easyway.


https://rclone.org/install/
