### ISSUE TITLE
405 error Method not allowed even if the site works

### ISSUE THREAD

**Issue by naguam** [dutchcoders/transfer.sh#329]
Hello,
So I set up a instance,
The site works well, It's great, but when I used `curl --head,` it showed error 405, method not allowed, is it normal ?
I thought it could be because of my nginx reverse proxy (miss configuration) but no : i also tested directly on the localhost:8080 (on the vm I run it) and I confirm the error 405 Method not Allowed (even if the site works).
Thank you.

**Comment by aspacca** [comment]
@naguam `HEAD` request is not supported on `/`

only on these two path patterns: https://github.com/dutchcoders/transfer.sh/blob/master/server/server.go#L389-L390

**Comment by naguam** [comment]
Ok thank you for the precision :) (didn't read all the code, maybe should I :+1: )

**Comment by kyodev** [comment]
hi
you can have a clean header with `curl --head -XGET url`
