### ISSUE TITLE
Power Shell invoke-webrequest : Unable to connect to the remote server

### ISSUE THREAD

**Issue by Siyu256** [dutchcoders/transfer.sh#333]
When I try to run file from powershell, I get the error of unable to connect to the remote server. Can anyone suggest? Thank you!

invoke-webrequest -method put -infile ./hello.txt https://transfer.sh/hello.txt
invoke-webrequest : Unable to connect to the remote server
At line:1 char:1
+ invoke-webrequest -method put -infile ./hello.txt https://transfer.sh ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : System.Net.WebException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by aspacca** [comment]
https://github.com/dutchcoders/transfer.sh#disclaimer

https://github.com/dutchcoders/transfer.sh/issues/326#issue-694925702
