### ISSUE TITLE
activating http basic auth

### ISSUE THREAD

**Issue by sicenul** [dutchcoders/transfer.sh#343]
I am using docker with local provider
I need to protect only authenticated user can upload a file.
is it possible by using http basic auth?
If so, how to setup using docker? and please also provide curl sample for uploading a file with auth.

Please enlighten me, thanks in advance

**Comment by aspacca** [comment]
hello @sicenul 
you have to set the following two ENV variables:
`HTTP_AUTH_USER`, `HTTP_AUTH_PASS`
https://github.com/dutchcoders/transfer.sh/blob/master/cmd/cmd.go#L247-L257

curl upload works just passing credentials in the URI: ie: `https://user:pass@domain.com/etc`

**Comment by sicenul** [comment]
great it work, thanks for your fast response.
