### ISSUE TITLE
Add option to disable inline handler

### ISSUE THREAD

**Issue by stek29** [dutchcoders/transfer.sh#344]
inline handler can be considered insecure (especially for self-hosted installations), since it allows direct view of any file type, including html files.
and allowing inline handler for html files leads to stored XSS via user uploaded content.
example: https://transfer.sh/inline/qEksd/test.html

**Comment by aspacca** [comment]
@stek29 I think that instead of disabling the inline handler we could sanitize the html content using bluemonday (https://github.com/microcosm-cc/bluemonday).
It's just a matter of adding at https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L1011
```
	if strings.HasPrefix(contentType, "text/html") {
		reader = ioutil.NopCloser(bytes.NewReader(bluemonday.UGCPolicy().SanitizeReader(reader).Bytes()))
	}
```

What do you think?

any content type other than `text/html` to sanitize?

**Comment by aspacca** [comment]
fixed with #347

**Comment by stek29** [comment]
@aspacca your solution seems good enough (.Contains html)
I’d still prefer to have an option to disable inline handler completely tbh, but yeah, it’s good enough

**Comment by stek29** [comment]
Is content type sanitized in any way? MIME types are case insensitive afaik, and from what i see it’s not lowercased anywhere

**Comment by aspacca** [comment]
you are right @stek29 :
https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L476-L480

I forgot that we use `mime.TypeByExtension` (that's lowercase) only if `content-type` header is emtpy
I will apply lowercase here: https://github.com/dutchcoders/transfer.sh/blob/master/server/handlers.go#L386

**Comment by aspacca** [comment]
@stek29 https://github.com/dutchcoders/transfer.sh/pull/355
what do you think?

I also reduced sanitzation to inline content disposition: ie, when you download the file you want it to be the original one

**Comment by stek29** [comment]
@aspacca do you mind making a release including these two fixes?

**Comment by aspacca** [comment]
done!
