### ISSUE TITLE
Print new line in transfer.sh

### ISSUE THREAD

**Issue by soulofmischief** [dutchcoders/transfer.sh#348]
The minified script offered on https://transfer.sh should have `printf "\n";` appended to the end of the function, so that the next bash prompt is on a new line and not the same line as the returned URL.

**Comment by aspacca** [comment]
@soulofmischief can you please refer to the file and line of code that has to be changed from the frontend repo: https://github.com/dutchcoders/transfer.sh-web/tree/master/src?

I guess it is somewhere here: https://github.com/dutchcoders/transfer.sh-web/blob/master/src/index.html

**Comment by soulofmischief** [comment]
@aspacca https://github.com/dutchcoders/transfer.sh-web/pull/35

**Comment by JustAnotherArchivist** [comment]
This would certainly be useful for manual terminal usage with e.g. curl. I've long had a little script that essentially does `curl --upload-file ...; echo` for this reason. However, the lack of a newline is great for automation as you'd otherwise have to strip it again to get the actual URL.

**Comment by stefanbenten** [comment]
We could simply handle with with an additional header.
The usages that i know of, prefer the current version, for ease of automation.

**Comment by stefanbenten** [comment]
@JustAnotherArchivist Did you see the example alias/function for the linux terminal? That would essentially be what you want for manual usage. Please correct me if there is any other manual way that wouldnt work with that?

**Comment by JustAnotherArchivist** [comment]
@stefanbenten Yeah, I'm aware of that. I originally wrote my script to work around percent-encoding bugs (#213 and #215) and still use it to `sed 's,%40,@,g'` because I prefer having the at sign in unencoded form. It also prints the deletion URL to stderr whereas it's normally silently swallowed.
