### ISSUE TITLE
Transfer.sh delete link not working

### ISSUE THREAD

**Issue by beriner** [dutchcoders/transfer.sh#351]
To reproduce:

1. Upload file and grab delete link
2. Send delete link from browser

Result: 
```
This page isn’t working. If the problem continues, contact the site owner.
HTTP ERROR 405
```

Manual delete via Curl etc. is working.

I don't know if it is config problem on website or problem in code.

**Comment by stefanbenten** [comment]
Hello @beriner !

The Browser does not use the DELETE request type, when entering the URL in your browser bar.

Curl specifies it specifically, hence that's why it's working.

The code is hereby working as intended.
Please let us know, if that does not explain the behavior!

**Comment by beriner** [comment]
Hi @stefanbenten ! I read through implementation discussion here: https://github.com/dutchcoders/transfer.sh/issues/44#issuecomment-399234697. 
So I understand it is not an issue with the code. It is the the website transfer.sh that should provide a delete form to process the delete GET-request, correct? So my wish would be that such a page would be set up for transfer.sh so that deletes can be successfully performed..

I'd also appreciate a reconsideration of that discussion. In my view a direct delete by a GET request (without DELETE header) should be made possible without the need for an additional form or button. To prevent accidental or malicious deletes via crawler the delete link should be constructed more randomly with longer passwords and should be different from the download links and not derived from them. I believe atm they are too similar and can be easily computed if the download link is known.

**Comment by stefanbenten** [comment]
Please open a new issue for this, since the above explained issue is not related to this specific issue any more (it is working as intended). 
Then we can start a better discussion including @aspacca on the new issue about possible solutions and the possibility of implementing that webpage.
