### ISSUE TITLE
``not found``

### ISSUE THREAD

**Issue by MiniXC** [dutchcoders/transfer.sh#352]
Any files uploaded at the moment simply return ``not found``.
I tried from several IPs and on both http and https.
File size also does not seem to matter as even tiny files return ``not found`` once uploaded.

**Comment by stefanbenten** [comment]
Can confirm the same, the files are present in the storage layer.
Seems like the latest bump yesterday introduced some changes, i'll check.

**Comment by stefanbenten** [comment]
Okay, issue resolved.

**Comment by MiniXC** [comment]
Thanks, didn't expect such a quick response!

**Comment by aspacca** [comment]
@stefanbenten was it something related to upstream or specific to the hosted service?

**Comment by stefanbenten** [comment]
Flags have changed from the version that was deployed before. I updated everything and it worked again.

**Comment by aspacca** [comment]
that was unexpected, what flags have changed?
