### ISSUE TITLE
I did not make my curl request with `-i`, is there no way to delete what I have uploaded by now?

### ISSUE THREAD

**Issue by l1ving** [dutchcoders/transfer.sh#354]
As the title says, I don't know my `X-Url-Delete` now. I uploaded something sensitive by accident, could I get in contact with one of the maintainers to delete it?

**Comment by stefanbenten** [comment]
Hello @l1ving !
You can reach out via email to me (found in my profile) with the problematic links and i'll get them removed.

We are currently working on a website/form for these requests.

**Comment by l1ving** [comment]
Thank you!
