### ISSUE TITLE
Curl failing: ssl certificate problem

### ISSUE THREAD

**Issue by TasinAyon** [dutchcoders/transfer.sh#357]
My uploads using curl is failing and i get this msg:

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by stefanbenten** [comment]
Issue has been resolved, automatic hook failed.
Thank you for reporting!
