### ISSUE TITLE
Support getting upload slot before upload

### ISSUE THREAD

**Issue by singpolyma** [dutchcoders/transfer.sh#36]
Would be nice if there were some way to request the eventual fetch URL first, then upload to it, then fetch from it thereafter.  This would simplify some scripting cases.

**Comment by singpolyma** [comment]
?

**Comment by aspacca** [comment]
@singpolyma I closed the issue since it was a two years old request. I'm doing some cleaning, you can open a new one if still a feature you want to be supported, but I see it very difficult to be implemented
