### ISSUE TITLE
[Server Issue] Transfer.sh keeps closing connections while uploading and downloading...

### ISSUE THREAD

**Issue by EMREOYUN** [dutchcoders/transfer.sh#360]
Hello,

As the your website does not working a "Contact Us" button(mentioned in #358), i'm writing my issue here.

While uploading a file(between 200M and 300M) from my server, transfer.sh server closes the connection weirdly without completing the upload..
While downloading one of my files to my computer, transfer.sh server also closes the connection at 64M,128M,192M or 256M without completing the download.

Can you look for the issues?

**Comment by EMREOYUN** [comment]
![ApplicationFrameHost_5Fy7jkNsNN](https://user-images.githubusercontent.com/35144629/114211680-9841d880-9969-11eb-840d-bcafd140ef4d.png)
Here is one of my test file failed to upload.

**Comment by EMREOYUN** [comment]
![image](https://user-images.githubusercontent.com/35144629/114311402-4333cd00-9af7-11eb-8040-98d719500585.png)

**Comment by stefanbenten** [comment]
The issue should be resolved and came from the underlying storage provider.
Please let me know, if you still encounter issues.

**Comment by EMREOYUN** [comment]
I tested right now and it uploaded as usual speed and correctly.
