### ISSUE TITLE
New feature: QRcode

### ISSUE THREAD

**Issue by netbofia** [dutchcoders/transfer.sh#363]
Hey, along with the url you could print-out a QRcode on the terminal. As an opt-in extra.

**Comment by stefanbenten** [comment]
Hey @netbofia ,

do you have an example how this should look like? How would an request via eg. curl look like?

**Comment by netbofia** [comment]
My initial though was that, the curl request was processed normally with the upload of the file. And the curl response might be some code that could be converted in the shell into a QR code. 

After second look, this isn't as trivial as I though since you can't make a QR code out of characters in the command-line, and I see that your landing have already has a QR code on it. 

I guess this can be closed, since rendering an image on the command-line is over kill and requires way to many plugins and dependencies.

Thank you for your consideration.
