### ISSUE TITLE
[QUESTION] Is there any API which returns the server settings.

### ISSUE THREAD

**Issue by MayankFawkes** [dutchcoders/transfer.sh#366]
Server settings includes the max file size and some basics.  because it will be good for development purpose and better than scraping.

**Comment by aspacca** [comment]
@MayankFawkes there's no API showing the server configuration. can you clarify what benefit such endpoint would bring for development purpose? I assume that if you are developing you are running your own instance and so you know what's the server setup.

**Comment by MayankFawkes** [comment]
Lets say i am building my some file sharing system with `transfer.sh`, since there are alot people using `transfer.sh` backend on public domain this might be useful to verify the file size before uploading the file. It might not useful for all users but its for me from my perspective. thanks
