### ISSUE TITLE
Can one configure the file hash size to increase security ?

### ISSUE THREAD

**Issue by parisni** [dutchcoders/transfer.sh#371]
`<domain>/11OFYI/bar.png` can the `11OFYI` string size be increased ? 6 charcacters makes brute force possible 
to discover files on the server

**Comment by aspacca** [comment]
thanks for the suggestion @parisni 
#372

**Comment by stefanbenten** [comment]
Fixed with https://github.com/dutchcoders/transfer.sh/commit/49c6d7ee4fda62d6334b87b1a9c8c1c6adea8018
