### ISSUE TITLE
Include handler errors in the log file

### ISSUE THREAD

**Issue by JustAnotherArchivist** [dutchcoders/transfer.sh#377]
I realised today that many messages only get logged to stderr, not to the log file. In particular, this includes all errors in the handlers, e.g. errors on reading from the storage (i.e. the `log.Printf` calls in `handlers.go`). I'd like to suggest having those both on stderr and in the log file (if one is specified).

**Comment by aspacca** [comment]
I will check @JustAnotherArchivist , thanks for reporting.

**Comment by stefanbenten** [comment]
I would suggest to chose either stderr or log, but not both.

**Comment by aspacca** [comment]
We should only rely on the logger instantiated in the cmd package: https://github.com/dutchcoders/transfer.sh/blob/master/cmd/cmd.go#L294

This will either use stdout or the log file if set (https://github.com/dutchcoders/transfer.sh/blob/49c6d7ee4fda62d6334b87b1a9c8c1c6adea8018/server/server.go#L160-L176)

The calls to `log.Printf` etc should be replaced by `logger.Printf` etc
