### ISSUE TITLE
self hosted transfer.sh reports the wrong URL when run behind TLS terminating web proxy

### ISSUE THREAD

**Issue by dburman** [dutchcoders/transfer.sh#378]
self hosted transfer.sh reports the wrong URI when run behind TLS terminating web proxy

Example:  
Running HA Proxy to to centralized TLS termination.  
transfer.sh is running in a docker
Public Internet URI:   https://transfer.example.com
reported URIs on the webpage & tool:  http://transfer.example.com/*

override option for hostname & protocol (https) ?

**Comment by cheeseandcereal** [comment]
Set your proxy to add the `X-Forwarded-Proto: https` header when forwarding traffic

**Comment by dburman** [comment]
Thanks!
