### ISSUE TITLE
[Server Issue] Transfer.sh once again uploads nothing

### ISSUE THREAD

**Issue by EMREOYUN** [dutchcoders/transfer.sh#381]
I can't upload anything on your server, it makes the speed very slow(sometimes directly 0)
![image](https://user-images.githubusercontent.com/35144629/124493357-36550b80-ddbe-11eb-9db2-80eed27c9c9f.png)

I also requested IP change from my host and new IP also having same issue. This is 4th time in this week(I upload once every day).
I also know what you guys want from me so there you go:
![image](https://user-images.githubusercontent.com/35144629/124493633-8af88680-ddbe-11eb-8f8a-838eea3c6c98.png)

**Comment by EMREOYUN** [comment]
![image](https://user-images.githubusercontent.com/35144629/124502401-14fb1c00-ddcc-11eb-99c4-91d6a6c721d1.png)
And it eventually started kicking us because connection speed is too low

**Comment by stefanbenten** [comment]
Hello @EMREOYUN,

can you please recheck? I cannot see any performance bottlenecks or limits currently.
I just uploaded a 8GB ISO Image just fine with 15MB/s avg speed.

**Comment by EMREOYUN** [comment]
> Hello @EMREOYUN,
> 
> can you please recheck? I cannot see any performance bottlenecks or limits currently.
> I just uploaded a 8GB ISO Image just fine with 15MB/s avg speed.

Today, it will better but still slow. I can't even pass 400kbps at all. Next backup run will happen tomorrow and i'll notify you the results.

**Comment by stefanbenten** [comment]
Thank you. Could you please let me know your request URL and IP by chance at the end? If sensitive, happy to receive them via mail.

**Comment by EMREOYUN** [comment]
For today, it seems good now, it uploaded the file at normal speed but it really depends by luck i guess.

**Comment by stefanbenten** [comment]
I am glad to hear that. I'll keep a closer eye on bandwidth and CPU util graphs for the next few days.
Would you be open to closing until you encounter very low speeds again (say less than 4-5MB/s)?

**Comment by EMREOYUN** [comment]
> I am glad to hear that. I'll keep a closer eye on bandwidth and CPU util graphs for the next few days.
> Would you be open to closing until you encounter very low speeds again (say less than 4-5MB/s)?

Of course, i'll reopen the issue if i encounter slow speeds. Thank you.
closed 381

**Comment by EMREOYUN** [comment]
![image](https://user-images.githubusercontent.com/35144629/125101999-80523000-e0e3-11eb-9dda-3a3105b6750e.png)
reopen #381
Issue still persist...

**Comment by stefanbenten** [comment]
@EMREOYUN I checked the usage graphs which were very low and showed no other failures in that timeframe.
The issue is not on the transfer.sh server itself from what i can say. Something that i noticed is that you are not using HTTPS, which you should.
`2021/07/09 17:29:50 Error putting new file: read tcp 144.76.136.153:80->93.190.9.161:63899: read: connection timed out`

**Comment by EMREOYUN** [comment]
> @EMREOYUN I checked the usage graphs which were very low and showed no other failures in that timeframe.
> The issue is not on the transfer.sh server itself from what i can say. Something that i noticed is that you are not using HTTPS, which you should.
> `2021/07/09 17:29:50 Error putting new file: read tcp 144.76.136.153:80->93.190.9.161:63899: read: connection timed out`

Https gives me even slower connections. I also contacted with my hosting and changed the machine before but it seems still happens.

**Comment by stefanbenten** [comment]
I had a script upload 1 50MB file every hour for the last 3 days. The slowest speed i got was 3MB/s (24Mbit/s).
Would you be able to just curl the webpage in that timeframe and see if that returns?

**Comment by EMREOYUN** [comment]
> I had a script upload 1 50MB file every hour for the last 3 days. The slowest speed i got was 3MB/s (24Mbit/s).
> Would you be able to just curl the webpage in that timeframe and see if that returns?

Ah i forgot to type earlier. I contacted with my host and they wanted me to convert the IP to static(IP address is already static but it will automaticly given by DHCP server). These 3 days, no issues with internet connection happened except sometimes it returns "Could not save file" sometimes. Why this error appears?

**Comment by stefanbenten** [comment]
I would have to check, but my guess is that the file either was bigger than originally specified. Could you send me timestamps of when those happened?

**Comment by EMREOYUN** [comment]
I don't have timestamps, you can check by the IP address. This is the only machine i ever struggled.

**Comment by stefanbenten** [comment]
@EMREOYUN I double checked and cannot find and request failures for your IP in that timeframe.

**Comment by EMREOYUN** [comment]
> @EMREOYUN I double checked and cannot find and request failures for your IP in that timeframe.

Weird, sometimes it returns that for no reason then.

**Comment by stefanbenten** [comment]
Next time it happens, please let me know and i'll scan all available logs manually, regardless of the IP.
I would propose to close the issue at this stage, since this does not seem to be caused by transfer.sh itself.

**Comment by EMREOYUN** [comment]
> Next time it happens, please let me know and i'll scan all available logs manually, regardless of the IP.
> I would propose to close the issue at this stage, since this does not seem to be caused by transfer.sh itself.

Alright, currently it seems fast enough to upload in last days. I'll let you know  if something new happens.

closed #381
