### ISSUE TITLE
Does not work on purge-days

### ISSUE THREAD

**Issue by wc7086** [dutchcoders/transfer.sh#391]
I used `purge-days` in the command, but `MaxDate` in `metadata` still shows as `0001-01-01T00:00:00Z`

transfer.sh version: transfer.sh 1.2.4: Easy file sharing from the command line

os: Linux 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64 GNU/Linux

Debian 10

**Comment by aspacca** [comment]
@wc7086 `purge-days` does not effect `MaxDate` in metadata. it deletes the files from the storage after the number of days setup

**Comment by wc7086** [comment]
> @wc7086 `purge-days` does not effect `MaxDate` in metadata. it deletes the files from the storage after the number of days setup

When I change servers, how does the program know when files need to be deleted?

**Comment by aspacca** [comment]
> When I change servers, how does the program know when files need to be deleted?

sorry, I forgot to answer your question

the logic is different according to backend storage: on s3 and storj the expiration date of the object for the bucket is set on upload, on local storage and gdrive it will delete any file that at any purge scans has the creation date + purge days after the time of the scan

**Comment by wc7086** [comment]
@aspacca 
Is the `Value` in `Usage` in README.md the default value? What happens if I don't set the value of `purge-days`? Does it mean keeping the file forever when I set `purge-days` to `0`?

**Comment by aspacca** [comment]
`0` is the zero value: it means that the feature is disabled.
In `REAMDE.md` no zero default value are reported.

@stefanbenten what do you think? Should we report them with something like `0 (disabled)`?
