### ISSUE TITLE
Feature: Check hash before web upload

### ISSUE THREAD

**Issue by wc7086** [dutchcoders/transfer.sh#392]
Verify the hash when uploading on the web, and save the hash field in the metadata. And display the hash field in the web interface. When using curl to upload, provide an upload option similar to `-H "sha1: <value>"`.

**Comment by aspacca** [comment]
@wc7086 what would the goal of implementing this?

**Comment by wc7086** [comment]
> what would the goal of implementing this?



> @wc7086 what would the goal of implementing this?

Gives the user a way to verify that the downloaded file is complete and correct. I don't know if providing hash on the download page is redundant, maybe we should wait until more people care about this option before deciding?

**Comment by aspacca** [comment]
The problem is that you have to trust the server: a malicious server could just receive and return the provided hash even after tampering the upload, and you should donwload the file a check his hash locally in order to be sure this didn't happen.
