### ISSUE TITLE
`random-token-length` The default length is 6, but the actual length is 7.

### ISSUE THREAD

**Issue by wc7086** [dutchcoders/transfer.sh#397]
`random-token-length` The default length is 6, but the actual length is 7.

**Comment by aspacca** [comment]
what release are you using?
latest master changed the `Token` function: https://github.com/dutchcoders/transfer.sh/blob/master/server/token.go#L37

**Comment by wc7086** [comment]
> what release are you using?
> latest master changed the `Token` function: https://github.com/dutchcoders/transfer.sh/blob/master/server/token.go#L37

Sorry, I forgot to mention the version number, I am using Releases v1.2.6.
