### ISSUE TITLE
Using storj storage without setting purge-days would cause upload fail

### ISSUE THREAD

**Issue by chencheyu** [dutchcoders/transfer.sh#398]
https://github.com/dutchcoders/transfer.sh/blob/d16a6cc25e14468db3cdb8ceca8fad0b792dec79/server/storage.go#L716

The default value of purge-days is 0. This causes the uplink to trigger an error (Invalid expiration time).
purge-days的預設值為0。會導致uplink觸發錯誤(Invalid expiration time)。

![擷取](https://user-images.githubusercontent.com/39858274/129471383-e97b5070-7b47-4ba7-9c7a-cde6a1908702.PNG)
![擷取2](https://user-images.githubusercontent.com/39858274/129471384-663e3c62-27ae-4cbd-92aa-0ce27f0eb1e7.PNG)

**Comment by aspacca** [comment]
@stefanbenten I've created a PR with a fix (#399 ), but can you double check this?
