### ISSUE TITLE
Multiple Files?

### ISSUE THREAD

**Issue by capsload** [dutchcoders/transfer.sh#40]
Hello,

im trying to upload multiple files within a folder to transfer.sh

Any idea how to do so?

transfer \* > /home/kvm1/www/uploads.txt

**Comment by omgbox** [comment]
transfer() {
  if [ $# -lt 1 ]; then
    echo -e "URL: https://transfer.sh"
    echo -e "Usage:   $0 <filename>"
    echo -e "Example: $0 file.zip file2.txt file3.jpg"
    return 1
  fi 
  myArray=( "$@" )
  for arg in "${myArray[@]}"; do
    tmpfile=$( mktemp -t transferXXX )
    if tty -s; then
      basefile=$(basename "$arg" | sed -e \'s/[^a-zA-Z0-9._-]/-/g\')
      curl --progress-bar --upload-file "$arg" "https://transfer.sh/$basefile" >> $tmpfile
      else curl --progress-bar --upload-file "-" "https://transfer.sh/$arg" >> $tmpfile
    fi
    cat $tmpfile
    rm -f $tmpfile
  done
}

**Comment by Arinerron** [comment]
Possible duplicate? https://github.com/dutchcoders/transfer.sh/issues/35
