### ISSUE TITLE
Question: Local driver files stored location

### ISSUE THREAD

**Issue by rajeshisnepali** [dutchcoders/transfer.sh#403]
Where are files stored if I run `docker run --publish 8080:8080 dutchcoders/transfer.sh:latest --provider local --basedir /tmp/` command? There are no files in `/tmp` directory or is it uploaded to `transfer.sh` servers.

**Comment by stefanbenten** [comment]
You need to mount the /tmp directory into the container. You just told the image to storage all of the data inside of the container in /tmp.
