### ISSUE TITLE
No URL returned after Upload

### ISSUE THREAD

**Issue by Lorenz1508** [dutchcoders/transfer.sh#406]
Hi
when i use this Command to upload a File it does not return any URL

`find -name ""test".r*" -exec curl --progress-bar -O -T {} https://transfer.sh/{} \; | grep -oE 'https://transfer.sh/.*/test.r.{2}' > test.txt`

After the files are uploaded successfully, the links are neither saved in test.txt nor displayed in the terminal !

**Comment by aspacca** [comment]
hi @Lorenz1508 , you are using `-O`: `Write output to a local file named like the remote file we get`
It seems that, while not file is getting, the output is saved to the local file named like the uploaded file.

You may want to report this to curl

**Comment by aspacca** [comment]
also `find` will return the whole relative path as `{}` placeholder, not just the filename, ending in something like:
`https://transfer.sh/./directory/filename.ext`

Something like should work:
```
find -name ""test".r*" -exec sh -c 'curl --progress-bar  -T {} https://transfer.sh/"$(basename "{}")"' \;
```
