### ISSUE TITLE
Website certificate has expired

### ISSUE THREAD

**Issue by rubikscraft** [dutchcoders/transfer.sh#408]
Exactly as the title says. HTTPS certificate for transfer.sh has expired.

**Comment by TomiScatto** [comment]
unable to upload via a bot

**Comment by ndom91** [comment]
include curl flag `-k` to ignore expired cert for now @TomiScatto

**Comment by automan0608** [comment]
seems your certbot crontab not work

**Comment by automan0608** [comment]
> include curl flag `-k` to ignore expired cert for now @TomiScatto

not work for me: 
curl: (7) Failed to connect to transfer.sh port 443: Connection refused

**Comment by automan0608** [comment]
@ndom91 not work for me 
curl: (7) Failed to connect to transfer.sh port 443: Connection refused

**Comment by stefanbenten** [comment]
Fixed, it wasnt certbot rather than the process itself not picking up the new cert.
