### ISSUE TITLE
Bug: Error 404 when try to delete file uploaded via zsh function

### ISSUE THREAD

**Issue by salmannotkhan** [dutchcoders/transfer.sh#409]
First of it doesn't give any deletion token when we upload file via zsh function/plugin
Another thing is it shows delete button whenever someone visits the link and it prompts for deletion token but when we click on confirm button it shows "Error (404) during deletion of file"

So, I'll suggest to remove delete button completely. and also I want to know when files deleted from the server?

**Comment by aspacca** [comment]
We won't remove the delete button, since it's working properly: you have to provide the deletion token, as stated in the hint.
When you click the button a `DELETE` request is made to `token/filename/deletionToken`, if the deletion token is wrong or empty, the request result in a 404 (not found)

Deletion token is returned on upload in the header `X-Url-Delete`, zsh function doesn't print it: I never used zsh so I wouldn't be able to modify. Any external PR to enanche the zsh function is welcome

**Comment by aspacca** [comment]
> I want to know when files deleted from the server

every server can setup it's own purge period.
If the server you've uploaded to is using `v1.3.0` the purge time is reported in the homepage

**Comment by salmannotkhan** [comment]
So I think it's useless to show that delete button

**Comment by salmannotkhan** [comment]
> Deletion token is returned on upload in the header `X-Url-Delete`, zsh function doesn't print it: I never used zsh so I wouldn't be able to modify. Any external PR to enanche the zsh function is welcome

Okay, I'll try that. Also when you click confirm again and again it appends the error into same error instead of replacing it completely.

**Comment by salmannotkhan** [comment]
Where I can find the script for transfer cli command?

**Comment by salmannotkhan** [comment]
>Also when you click confirm again and again it appends the error into same error instead of replacing it completely.

nvm I made PR on transfer.sh-web repo for that fix

**Comment by imTHAI** [comment]
> Deletion token is returned on upload in the header `X-Url-Delete`, zsh function doesn't print it: I never used zsh so I wouldn't be able to modify. Any external PR to enanche the zsh function is welcome

That's why ! I was searching where the hell I should be supposed to have received it. Maybe it would be good to warm people somewhere in the README.md text, zsh is even the default shell under MacOS

**Comment by corporateuser** [comment]
Some command line clients do not print headers by default, please consider to return JSON object instead of a simple string:
```JSON
{
  downloadUrl: string,
  deletionURL: string
}
```

**Comment by aspacca** [comment]
@corporateuser sorry, that will be a breaking change
