### ISSUE TITLE
Alias for fish-shell

### ISSUE THREAD

**Issue by awendland** [dutchcoders/transfer.sh#41]
I would like to add this function for [fish-shell](https://fishshell.com/) somewhere in the documentation, but I'm unsure as to where.

``` fish
function transfer --description 'Upload a file to transfer.sh'
    if [ $argv[1] ]
        # write to output to tmpfile because of progress bar
        set -l tmpfile ( mktemp -t transferXXX )
        curl --progress-bar --upload-file $argv[1] https://transfer.sh/(basename $argv[1]) >> $tmpfile
        cat $tmpfile
        command rm -f $tmpfile
    else
        echo 'usage: transfer FILE_TO_TRANSFER'
    end
end
```

**Comment by k0nsl** [comment]
@awendland: see if you can have them add your fish-shell function here:
https://transfer.sh/#samples

**Comment by SimplyY** [comment]
Thanks a lot! 

I used it, it is very useful . I think it should be added in README.

My PR  https://github.com/dutchcoders/transfer.sh/pull/46

**Comment by CrashyBang** [comment]
:+1:

**Comment by dbazuin** [comment]
Works fine, thanks awendland.
