### ISSUE TITLE
No `x-url-delete` header when sending POST request

### ISSUE THREAD

**Issue by anihm136** [dutchcoders/transfer.sh#419]
I noticed that the `x-url-delete` header is not being set when the user uploads a file via post request. Is uploading files via POST deprecated? (since all the examples seem to use PUT requests instead). If not, I think the header should be set correctly

**Comment by anihm136** [comment]
If this is indeed an omission, I would propose to merge the handlers for the POST and PUT requests. Instead, handling filename resolution can be separated into different functions based on the request method, since that seems to be the only difference between the two functions

**Comment by anihm136** [comment]
Is `POST` meant to be officially supported? If not, I could remove the post-related handlers and logic, else I can add the header

**Comment by aspacca** [comment]
@anihm136 I honeslty don't have much visibility on the clients, I think that listing them on this repo could be valuable as well. could you help on that?

as for the `POST` handler, happy to remove indeed: but not before auditing as much as possible the clients around and how many of them rely on it.

in the meanwhile you're welcome to add the `x-url-delete` headers to the `POST` handler

**Comment by anihm136** [comment]
I agree that it would be useful to list other clients here. I only know of a couple so far, but I'd be happy to help find and list more of them. In the meantime I'll add the headers to the post handler

**Comment by aspacca** [comment]
@anihm136 great, thanks. looking forward for the PR

**Comment by anihm136** [comment]
I have created a PR for adding the headers. Let me know how you'd like to begin work on listing existing clients (new issue, GH discussion or any other), and I can start listing some of the ones I've come across

**Comment by aspacca** [comment]
>I have created a PR for adding the headers

thanks, see my comment

>Let me know how you'd like to begin work on listing existing clients 

either an issue or a GH discussion is fine for me
