### ISSUE TITLE
No error returned when Max-Days is invalid

### ISSUE THREAD

**Issue by anihm136** [dutchcoders/transfer.sh#420]
When a file is uploaded with a very high value set for `Max-Days` header, the server returns a URL. However, the URL leads to a 404 page

**Expected behavior**:
The server should return an appropriate 400 response when an invalid value is set for the header

**Comment by kugiyasan** [comment]
Hey can I take this issue?

**Comment by aspacca** [comment]
@anihm136 how much high the value must be set?

**Comment by anihm136** [comment]
Maybe overkill, but I did a binary search and it appears to fail at 8217934 days

**Comment by jimmybrancaccio** [comment]
Looks good now @aspacca and @kugiyasan Thank you both! ❤️
