### ISSUE TITLE
Support for pasting files directly?

### ISSUE THREAD

**Issue by fr3fou** [dutchcoders/transfer.sh#425]
Let's say I have an image copied in my clipboard, I'd like to simply press <kbd>Ctrl</kbd>+<kbd>V</kbd> or <kbd>⌘</kbd>+<kbd>v</kbd> while on the frontend and have that start the upload automatically. Would you consider adding support for this? I think https://imgur.com has it

**Comment by glk0** [comment]
HI, I'd like to work on this feature. Can you assign it to me ?

**Comment by stefanbenten** [comment]
Of course!

**Comment by aspacca** [comment]
@glk0 thanks

in caes the code for the fronted is at https://github.com/dutchcoders/transfer.sh-web

**Comment by aspacca** [comment]
fixed by https://github.com/dutchcoders/transfer.sh-web/pull/58
