### ISSUE TITLE
Contact us button redirects to top of the page

### ISSUE THREAD

**Issue by jimdevops19** [dutchcoders/transfer.sh#429]
I tried to contact someone for support on what to do in case of a forgotten token for deleting a file. But the contact us button in https://transfer.sh was not leading to a page where I can describe my problem.

Thanks a lot

**Comment by aspacca** [comment]
@jimdevops19 I will use this issue for fixing the functionality on UI

as for the delete token you can try to reach @stefanbenten , he's the one the manage the hosted instance at  https://transfer.sh

**Comment by aspacca** [comment]
proposed fix: add a param to the CLI for the `contact us` email address and transform the link to a `mailto:` one pointing to that value.
if no param is provided do not rendere the `contact us` section

**Comment by stefanbenten** [comment]
I would be fine with that!
