### ISSUE TITLE
syntax error in bashrc script

### ISSUE THREAD

**Issue by kevjonesin** [dutchcoders/transfer.sh#43]
Both the transfer.sh script [at gist](https://gist.github.com/nl5887/a511f172d3fb3cd0e42d) and the two line .bashrc version [in 'sample use cases'](https://transfer.sh/) return ...

> syntax error near unexpected token `('

... when running in bash via Manjaro Linux.

In the case of calling the script from my bashrc I get ...

> [kevjo@manjaro ~]$ transfer test-transfer.txt 
> 
> bash: /home/kevjo/Software/Scripts/transfer.sh: line 14: syntax error near unexpected token `('
> 
> bash: /home/kevjo/Software/Scripts/transfer.sh: line 14: `transfer() { '

... Inserting the two line snippet version directly in .bashrc results in similar, but with an error line number relevant to location in the bashrc file itself.

Might something be missing from within or preceding the round brackets at "transfer()" perhaps?

**Comment by pepa65** [comment]
This is a ``fish`` file, not for bash/zsh.
