### ISSUE TITLE
Request to add a github action to the repo

### ISSUE THREAD

**Issue by Jassi10000** [dutchcoders/transfer.sh#430]
This is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by aspacca** [comment]
hi @Jassi10000 thanks for the offer, but I'd rather welcome everyone personally as long as the number of contributions allow me to do that :)
