### ISSUE TITLE
Bunch of persons/computers uploading files to the same url/folder

### ISSUE THREAD

**Issue by leoheck** [dutchcoders/transfer.sh#434]
Bunch of persons/computers uploading files to the same url/folder
Is this possible?

I have a script that makes some questions, and I would like to have the answers uploaded the same place online.

Is this possible with transfer.sh?

**Comment by aspacca** [comment]
@leoheck on your own hosted instance?

probably, setting `--random-token-length`/`RANDOM_TOKEN_LENGTH ` to zero

not on hosted transfer.sh

**Comment by leoheck** [comment]
@leoheck on your own hosted instance?

On any free/public/available.
Or, is it possible to set up a host with this tool?
If yes, then it can be mine.

Could you give me an example before closing this issue?

**Comment by aspacca** [comment]
I doubt any free/public/available instance have 0 length for the random token 

How proficient are you in running a service on internet?
This could be a starter:
https://github.com/dutchcoders/transfer.sh#docker

Something like:
```
docker run -v /the/folder/you/want/to/save/to:/tmp --publish 80:8080 dutchcoders/transfer.sh:latest --provider local --basedir /tmp/ --random-token-length 0
```

Beware that if the users will upload files with the same name it could be a problem (not sure the latest will be saved or the first only, and later ones will fail)

**Comment by aspacca** [comment]
>Beware that if the users will upload files with the same name it could be a problem

Every new upload with the same filename will overwrite the old one

Also you will be able to access the files only from the local folder, `http://youdomain.com//filename.ext` won't work

**Comment by leoheck** [comment]
> How proficient are you in running a service on internet?
I can handle it.

> Every new upload with the same filename will overwrite the old one
Ok.

> Also you will be able to access the files only from the local folder, http://youdomain.com//filename.ext won't work
Ok

Thanks @aspacca
