### ISSUE TITLE
[Server Issue]Constant 413 Entity Request Too Large errors

### ISSUE THREAD

**Issue by EMREOYUN** [dutchcoders/transfer.sh#436]
cURL requests returns 413 Entity Request Too Large errors everytime i try to upload a file between 300-330 MB. Did limits changed or can you check any issues on the server?
Edit: Same happens in website GUI upload.
![chrome_uO2qXJESIY](https://user-images.githubusercontent.com/35144629/142767403-233889ce-ff70-4ec6-9e1e-b24da3f3d965.png)
![chrome_zbVd7xcwaT](https://user-images.githubusercontent.com/35144629/142767404-0b32ee5c-dd4a-44f5-ae5f-ed5425376aa7.png)

**Comment by stefanbenten** [comment]
Should be functional again. Sorry for the short failure time.
