### ISSUE TITLE
Error I get when trying to upload a jpeg image using curl

### ISSUE THREAD

**Issue by DillFrescott** [dutchcoders/transfer.sh#437]
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

**Comment by DillFrescott** [comment]
Please ignore the markdown kind of messing with the error since its in html

**Comment by stefanbenten** [comment]
How do you try to upload it? @DillFrescott 
A full example would be great.

**Comment by DillFrescott** [comment]
Here is the exact console history of my latest attempt. This is very odd. Perhaps its my antivirus or firewall?

https://gist.github.com/DillFrescott/e1e21817a2630fc4dd87ceafc7ddeb48

**Comment by DillFrescott** [comment]
Update: Just disabled the antivirus and firewall and its still happening...

**Comment by stefanbenten** [comment]
You need to specify https://transfer.sh as endpoint. The redirect comes from HTTP to HTTPS.

**Comment by DillFrescott** [comment]
Ok, that works, but I no longer have an upload progress :(

**Comment by stefanbenten** [comment]
That sounds like an unrelated issue to me (also not tied to transfer.sh).

**Comment by DillFrescott** [comment]
Ok.
