### ISSUE TITLE
transfer.sh Moved Permanently

### ISSUE THREAD

**Issue by nlkguy** [dutchcoders/transfer.sh#438]
~$ curl http://transfer.sh/ --upload-file exp3.zip 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

**Comment by stefanbenten** [comment]
See #437 , you need to use https!

**Comment by nlkguy** [comment]
~$ curl https://transfer.sh/ --upload-file backup.log 
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

back then transfer.sh only worked with'out' https! , now neither are working

**Comment by stefanbenten** [comment]
Om 2021, almost 2022 there is no reason to still use non SSL sites.
I just confirmed that uploads as well as downloads work fine.
