### ISSUE TITLE
direct link for fullscreen video

### ISSUE THREAD

**Issue by mcreasindo-git** [dutchcoders/transfer.sh#439]
Hi,
* If we send video file, is it possible to share the direct link for fullscreen video?
* the purpose is very simple use case, people with direct link can play the video immediately.

**Comment by aspacca** [comment]
hi @mcreasindo-git 
you are looking for the inline alias: https://github.com/dutchcoders/transfer.sh/blob/6b8eff83220b8ae48bbea408309ca6c6234a9862/README.md#link-aliases
