### ISSUE TITLE
What all types of "--provider" do we have while launching it with docker

### ISSUE THREAD

**Issue by AmoghSaxena** [dutchcoders/transfer.sh#442]
I want to launch it with domain name instead of IP. 
But while i run the docker command to run the container and go to the custom domain assigned to it.
It shows the IP address as a title bar and other upload settings.
Can anyone help me with this ?

**Comment by stefanbenten** [comment]
@AmoghSaxena Could you provide the full example of how you try to start it?
More than happy to assist!

**Comment by stefanbenten** [comment]
@AmoghSaxena Any update on this?

**Comment by AmoghSaxena** [comment]
> @AmoghSaxena Any update on this?

I want to deploy the project on my private FQDN but it only gives me the option for IP address instead of putting a domain.

**Comment by mckaygerhard** [comment]
> > @AmoghSaxena Any update on this?
> I want to deploy the project on my private FQDN but it only gives me the option for IP address instead of putting a domain.

read the requirements it said: "_Could you provide the full example of how you try to start it?_" so @AmoghSaxena  without further details nobody can help you..

**Comment by aspacca** [comment]
@AmoghSaxena
https://pkg.go.dev/net#Dial
according to the documentation 
```
For TCP and UDP networks, the address has the form "host:port". The host must be a literal IP address, or a host name that can be resolved to IP addresses
```

as @mckaygerhard said indeed, without further details we cannot help with a possible solution

**Comment by stefanbenten** [comment]
@AmoghSaxena Is this question still unanswered? Else i am going to close it in 48 hours from now.
