### ISSUE TITLE
Is there any kind of documentation to set this up with docker other than the README?

### ISSUE THREAD

**Issue by driftywinds** [dutchcoders/transfer.sh#445]
The readme has very little information and I was wondering if anyone had made a guide to set this up with docker?

**Comment by aspacca** [comment]
@driftywinds 
do you have any specific issue?

starting from fixing your setup we can come out with better documentation

**Comment by driftywinds** [comment]
> @driftywinds do you have any specific issue?
> 
> starting from fixing your setup we can come out with better documentation

@aspacca firstly, the rclone integration fails to work for me and my bucket is not connected even though I supplied the relevant keys and IDs.
Secondly, even though the docker container starts up successfully, I am not able to connect to it remotely. I have checked and rechecked everything including the forwarded ports or any other hindrance but I can't connect to it.

**Comment by aspacca** [comment]
@driftywinds this doesnàt seem related to docker

also, could please share the params you use to launch transfer.sh and please, do not attacch screenshot with output, copy the text :)

**Comment by driftywinds** [comment]
@aspacca My bad, here is the command I use to deploy the container - 
```
sudo docker run --publish 8080:8080 dutchcoders/transfer.sh:latest --provider storj --storj-access <access token> --storj-bucket vaultwarden
```

**Comment by driftywinds** [comment]
> @driftywinds this doesnàt seem related to docker
> 
> also, could please share the params you use to launch transfer.sh and please, do not attacch screenshot with output, copy the text :)

From my untrained eye it seems like it is not able to connect to Storj servers, is that it?

**Comment by stefanbenten** [comment]
It looks like you have some sort of local DNS problem. Also why do you start it with `sudo` ?

**Comment by driftywinds** [comment]
> It looks like you have some sort of local DNS problem. Also why do you start it with `sudo` ?

Oh I didn't know I was not supposed to use sudo, it has always been a constant

**Comment by stefanbenten** [comment]
Ok it sounds like your user is not part of the docker group then. Its always preferred to run with as few priviliges as possible :)

This however isnt the problem here. The screenshot above clearly indicates a DNS lookup failure.

**Comment by driftywinds** [comment]
> Ok it sounds like your user is not part of the docker group then. Its always preferred to run with as few priviliges as possible :)
> 
> This however isnt the problem here. The screenshot above clearly indicates a DNS lookup failure.

I host other things on the same VPS and they seem to connect just fine with whatever they need to, could it be a problem with StorJ servers? I'm sorry I am a novice at this so I do not know what I can do to fix it.

**Comment by stefanbenten** [comment]
The Storj Servers are not the problem. Its the DNS lookup of the container that fails. I do not have the time to test the docker image myself in the next few hours, but i also doubt that the image itself is the issue.
Which VPS provider are you using?

**Comment by driftywinds** [comment]
> The Storj Servers are not the problem. Its the DNS lookup of the container that fails. I do not have the time to test the docker image myself in the next few hours, but i also doubt that the image itself is the issue. Which VPS provider are you using?

After looking into it I found out that it was a problem with my docker version. Thank you for your help guys! 
One last thing - 
when I try to delete a file from the UI after uploading from the command line, what token am I supposed to give to it? Uploading from UI gives a deletion token but the command line does not

**Comment by stefanbenten** [comment]
@driftywinds Glad it works now!
Regarding the deletion token, please see https://github.com/dutchcoders/transfer.sh/issues/419

**Comment by driftywinds** [comment]
Thank you!
