### ISSUE TITLE
Dead v2 onion address

### ISSUE THREAD

**Issue by JacksonChen666** [dutchcoders/transfer.sh#446]
[Onion addresses for version 2](https://support.torproject.org/onionservices/v2-deprecation/) has been officially killed by the tor project at least months ago, and I am not aware of any new onion addresses or even [a redirect for tor users](https://community.torproject.org/onion-services/advanced/onion-location/) for it (yes, i tested).

So far, I think only the following can be done about it:
- Get a new onion address
    - [With redirect for tor users](https://community.torproject.org/onion-services/advanced/onion-location/) (recommended)
    - Without auto redirect and update the address on the page
- Delete the appearance of the onion address on the page

**Comment by stefanbenten** [comment]
@JacksonChen666 Thanks for bringing it up! I did notice that as well recently.

@aspacca I would be in favor of removing it for the time being.

**Comment by aspacca** [comment]
@stefanbenten 
let's delete it: I indeed didn't notice it when I refactored the frontend to use custom domain for self hosting
