### ISSUE TITLE
Transfer.sh can't be reached?

### ISSUE THREAD

**Issue by siddharthchaini** [dutchcoders/transfer.sh#450]
I am unable to open transfer.sh

I tried opening it on wifi and data, on Chrome as well as Firefox.

I think it's just me though. Any idea what could be the reason?

Here's what chrome tells me:
```
This site can’t be reached
The webpage at https://transfer.sh/ might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR

```
![transfer](https://user-images.githubusercontent.com/40721514/147264449-69e5e671-9a8c-4d03-b952-de55acbcac3d.PNG)

**Comment by stefanbenten** [comment]
You are very likely hitting the geo-blocking which transfer.sh sadly had to implement due to abuse recently.
I could look into returning a 403 Access Denied if that helps?

**Comment by mckaygerhard** [comment]
> You are very likely hitting the geo-blocking which transfer.sh sadly had to implement due to abuse recently. I could look into returning a 403 Access Denied if that helps?

umm this means that now we must be open to be traking by? due those abusers?

**Comment by stefanbenten** [comment]
@mckaygerhard Until further notice we are not able to provide services to a couple of regions/countries, since those have been massively abusing the service. However i will be working on a better error message to reflect this.

**Comment by mckaygerhard** [comment]
we must provide a list of countries and reasons why .. also we must made another way to stop abusers, or a way to provide those users help to the service..

**Comment by stefanbenten** [comment]
@mckaygerhard We are currently working on improving upon this.
That said, we cannot fully mitigate it which also one of the reasons that most public services without registration had to shutdown (one example being Firefox Send).

**Comment by siddharthchaini** [comment]
> @mckaygerhard Until further notice we are not able to provide services to a couple of regions/countries since those have been massively abusing the service. However, I will be working on a better error message to reflect this.

That's really a bummer. I really liked using transfer.sh and it sucks that because of other abusers I won't be able to use it. 

Anyway, thank you for clearing this out. I'll search for alternatives.

**Comment by mckaygerhard** [comment]
the 99% of the abusers are windoser stupid users.. but i noted also the most activity is supporting windos related stupid features like clavmav! @siddharthchaini and @stefanbenten so in part this is a right consecuence.. well deserved!

**Comment by aspacca** [comment]
@mckaygerhard 
Use of harsh language is against the code of conduct

**Comment by OfekShochat** [comment]
> we must provide a list of countries and reasons why .. also we must made another way to stop abusers, or a way to provide those users help to the service.
Can you provide a list?
