### ISSUE TITLE
Is site transfer.sh dead ?

### ISSUE THREAD

**Issue by raul1991** [dutchcoders/transfer.sh#456]
Hey! everyone,

I've been seeing a dns lookup failure for the website. Has it been shutdown ? Is there an alternative for it ?

**Comment by stefanbenten** [comment]
Hello @raul1991

Seems like it is an issue on your end, it resolves fine for all resolvers i tried so far:

```
nslookup transfer.sh 1.1.1.1
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   transfer.sh
Address: 144.76.136.153
```

Please check your local setup :)

**Comment by raul1991** [comment]
@stefanbenten just tried and it still shows a dns failure.

![Screenshot_20220101_020556_com.android.chrome.jpg](https://user-images.githubusercontent.com/1281636/147838414-82262526-6c32-4933-8971-f582189634f5.jpg)

**Comment by stefanbenten** [comment]
This is not a DNS failure rather than geoblocking.
Please see for reference #444
