### ISSUE TITLE
Link with invalid characters errors out

### ISSUE THREAD

**Issue by matteoturini** [dutchcoders/transfer.sh#457]
https://transfer.sh/FXtvbX/DiscordSRV-Build-1.24.0.jar%E2%8F%8E for example says ``runtime error: invalid memory address or nil pointer dereference``

**Comment by stefanbenten** [comment]
That seems like its some kind of other bug..
@aspacca Do you have time to diagnose?

**Comment by stefanbenten** [comment]
I found the issue and it is not related to invalid characters. It was an internal nil pointer that was passed to a clean up func, that caused this.

**Comment by aspacca** [comment]
hi @stefanbenten

sorry, I was away, thanks for taking care of the issue
