### ISSUE TITLE
504 gateway time-out response from server

### ISSUE THREAD

**Issue by Anarios** [dutchcoders/transfer.sh#466]
Uploading 10GB tar.gz file via `transfer` function provided in examples.

The file gets sent (I see network activity).

But then, after some wait - I receive a 504 error

**Comment by Anarios** [comment]
Same happened from web UI.

**Comment by stefanbenten** [comment]
Hello @Anarios , could you please try again?
Since the file is being ran through a virus scanner and then afterwards being uploaded, there might have been the case that the instance timed out waiting on the application response. I have increased said timeouts to avoid this now.

**Comment by Anarios** [comment]
Same error. The tar.gz is a huge csv file archived (in case this info helps)

**Comment by Anarios** [comment]
Doesn't seem like I can reopen the issue, though, @stefanbenten

**Comment by stefanbenten** [comment]
Do you have a filename and timestamp for me? You can submit those via the website contact form if privacy should be kept.

**Comment by Anarios** [comment]
> Do you have a filename and timestamp for me?

Filename is topRated.tar.gz. No exact timestamp, but I left a comment here pretty-much immediately. So should be within a minute or two around the comment post time.

**Comment by stefanbenten** [comment]
Thank you, i will look into this.

**Comment by stefanbenten** [comment]
@Anarios Could you kindly try again?
Thank you!

**Comment by Anarios** [comment]
@stefanbenten, all good now, thanks!

**Comment by joshlopes** [comment]
@stefanbenten having the same on self-hosted .. can you please enlight me -- what have you done ?
