### ISSUE TITLE
Support for folder upload/sharing

### ISSUE THREAD

**Issue by spantheslayer** [dutchcoders/transfer.sh#469]
whenever I want to share multiple files, it becomes very difficult to upload multiple files at once. It would be awesome if devs can implement this feature. Looking forward to it.

**Comment by aspacca** [comment]
hi @spantheslayer this is already support throught `POST` requests.
I see it's not properly documented, you can find some context here: https://github.com/dutchcoders/transfer.sh/issues/419

**Comment by spantheslayer** [comment]
And what about folders? Is it possible?

**Comment by aspacca** [comment]
You have to pack the folder before uploading

https://transfer.sh/ has multiple examples of different way to upload content
