### ISSUE TITLE
Install on a raspberry pi?

### ISSUE THREAD

**Issue by camdenorrb** [dutchcoders/transfer.sh#47]
I can't seem to get docker to host it's own transfer.sh site. `pi@raspberrypi:/opt $ cd transfer.sh
pi@raspberrypi:/opt/transfer.sh $ docker build -t transfersh .

Sending build context to Docker daemon 2.358 MB
Step 1 : FROM golang
latest: Pulling from library/golang
efd26ecc9548: Pull complete 
a3ed95caeb02: Pull complete 
d1784d73276e: Pull complete 
72e581645fc3: Pull complete 
01ce90e06b06: Pull complete 
666886c80650: Pull complete 
2b9aef313bfc: Pull complete 
a47658d1602e: Pull complete 
Digest: sha256:d93f678ece9be3e1b5c8d845892fd5d469c8cb8aef335cee8df63c41d0f60818
Status: Downloaded newer image for golang:latest
 ---> a274681c9df8
Step 2 : MAINTAINER Remco Verhoef <remco@dutchcoders.io>
 ---> Running in 819bc2ab9d32
 ---> 1bc96b6d1c8c
Removing intermediate container 819bc2ab9d32
Step 3 : RUN mkdir -p /go/src/app
 ---> Running in 772ee128ed22
exec format error
Cannot start container 772ee128ed223d3e66ae4a779dec07375e5d06d33f81404029976973e6712504: [9] System error: exec format error
pi@raspberrypi:/opt/transfer.sh $ docker run --publish 8080:8080 --rm transfersh --provider local --basedir /tmp/
Unable to find image 'transfersh:latest' locally
Pulling repository docker.io/library/transfersh
docker: Error: image library/transfersh not found.
See 'docker run --help'.
pi@raspberrypi:/opt/transfer.sh`

Any ways I can host it on my raspberry pi? if so any help is appreciated :)

**Comment by schollz** [comment]
I don't know Docker, but why not just build with Go? After you [install Go](https://golang.org/dl/) just use:

```bash
git clone https://github.com/dutchcoders/transfer.sh.git
cd transfer.sh/transfersh-server/
go get ./... 
find . -type f | xargs sed -i 's/transfer.sh/YOURSERVER/g'
go build
```

Make sure to replace `YOURSERVER` with your DNS so it defaults to your server on the webpage and in the code. Then run 

```bash
./transfersh-server -provider=local -basedir=/tmp
```

**Comment by camdenorrb** [comment]
How do I install Go?

**Comment by schollz** [comment]
Download and install:
```
wget https://storage.googleapis.com/golang/go1.6.2.linux-armv6l.tar.gz
sudo tar -C /usr/local -xzf go1.6.2.linux-armv6l.tar.gz
```

Add a `work` directory to store Go dependencies.
```
mkdir ~/work
```

Then `nano ~/.profile` to add these lines:

```
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/work
```

That's it! Test with 

```
-> % go version
go version go1.6.2 linux/arm
```

**Comment by camdenorrb** [comment]
Thx ^-^
