### ISSUE TITLE
service side encryption for local backend

### ISSUE THREAD

**Issue by fnpanic** [dutchcoders/transfer.sh#471]
Hi,

it would be great to have server side encryption for localbackend by passing a password as a header and then encrypting it with AES. On download the password should be passed to the server.

The server itself das not store the passwords and so has encryption at rest.

**Comment by aspacca** [comment]
hi @fnpanic 

there is still open a PR I worked on long time ago: https://github.com/dutchcoders/transfer.sh/pull/162

there are some concerns having the encryption on server side since you have to trust the server obviously.

**Comment by fnpanic** [comment]
@aspacca Thanks for your feedback! That is exactly what i was thinking about. The downsides are clear but it is really a good solution for encryption at rest. 

Any chance to get this merged?

**Comment by aspacca** [comment]
@fnpanic revamped it

but I can see this: https://github.com/golang/go/issues/44226

@stefanbenten what do you think?

**Comment by aspacca** [comment]
I forgot: you can achieve the same goal with https://github.com/dutchcoders/transfer.sh#encrypt--upload

**Comment by fnpanic** [comment]
Yes it does but if you download it form a windows box it is not very easy to decrypt it on the fly. That is why i think your patch is a great fit here.
