### ISSUE TITLE
Reporting Abuse

### ISSUE THREAD

**Issue by isaacKenyon** [dutchcoders/transfer.sh#472]
I've come across a file hosted on your website which I am certain to be malicious.

I was on the website and did not see a form to report abuse, so I figured my next option was to leave it here since emails are scary 😥

## URL in question:
`https://transfer.sh/get/BGCth5/Ngame%20v2.4.rar`

## Why I believe it to be malicous:
Recently there have been floods of phishing links on Discord, they follow the same general principle of "Hey can you test my game? [URL]". 

I recently got a message which follows that format and so I am confident that it is abuse too. 
![image](https://user-images.githubusercontent.com/87788699/158071131-e4d25632-b02f-45db-98b9-e5d3e4547de0.png)

**Comment by stefanbenten** [comment]
Hello @isaacKenyon,

thanks for reporting. The file has been removed.
For the future, there is a contact us button near the end of the page, which definitely gets handled as well!

Cheers!
