### ISSUE TITLE
[Demand] Can provide a list of historical files on the page

### ISSUE THREAD

**Issue by wisinfun** [dutchcoders/transfer.sh#477]
You can easily find historical files to prevent repeated uploading

**Comment by aspacca** [comment]
hello @wisinfun , not sure I understand what you mean

**Comment by wisinfun** [comment]
> hello @wisinfun , not sure I understand what you mean

like this，It would be better to have a search box
<img width="1401" alt="CleanShot 2022-04-05 at 14 24 17@2x" src="https://user-images.githubusercontent.com/41355260/161691926-ffe9cad8-55dc-47d6-a262-8ad92934d0be.png">

**Comment by aspacca** [comment]
the problem is that such feature makes sense only in self-hosted *and* single upload user case
