### ISSUE TITLE
Transfer.sh alias mangles output for hidden onion service

### ISSUE THREAD

**Issue by BoBeR182** [dutchcoders/transfer.sh#48]
https://gist.github.com/BoBeR182/27ef189e6a61ca5add5c123c558a29d4
Is what I am using for my alias

When doing the following command.

transfer files.zip

I get an incorrect URL with an invalid SSL cert. See log below...

[bober@boberbot][~]% transfer files.zip 
###### ################################################################## 100.0%

https://jxm5d6emw5rknovg.onion/9EZaY/files.zip

If a file is uploaded via the onion hidden service the output from the server should be without SSL.

**Comment by nl5887** [comment]
Fixed with commit @2eb2d1d7f4526eff86f235667286284457c1585b
