### ISSUE TITLE
would it be possible to set/use authorization tokens to limit who can upload?

### ISSUE THREAD

**Issue by andrewzah** [dutchcoders/transfer.sh#487]
I want to create an instance to let some people upload, but only if they pass an authorization token. This is different than the basic auth handler, which doesn't make sense for multiple people.

This could be an array of strings, statically set in the config.

**Comment by aspacca** [comment]
there's the option to ask for an http basic authorization:
```
http-auth-user | user for basic http auth on upload |   | HTTP_AUTH_USER
-- | -- | -- | --
http-auth-pass | pass for basic http auth on upload |   | HTTP_AUTH_PASS

```

**Comment by andrewzah** [comment]
Is it possible to set multiple? Ideally I’d like to set a token per person in case it needs to be revoked or changed.

**Comment by aspacca** [comment]
@andrewzah 
it's not possible to set multiple credentials: I will look into in ad an `--http-auth-htpasswd` param so that the credentials are read from an htpasswd file

**Comment by aspacca** [comment]
> I will look into in ad an `--http-auth-htpasswd` param so that the credentials are read from an htpasswd file

I will work on it as soon I'll have a little more time

**Comment by aspacca** [comment]
@andrewzah see #537
