### ISSUE TITLE
Can't connect to transfer.sh anymore!

### ISSUE THREAD

**Issue by GACGAMA** [dutchcoders/transfer.sh#494]
Hello everyone

I'm using curl on my archlinux server. After an update on the system, when I try:

`curl --upload-file file.tar https://transfer.sh/file.tar`

I get:

`curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to transfer.sh:443                                                                                                                                                                                                 
`

**Comment by stefanbenten** [comment]
Closing, since its very likely due to geoblocking mentioned here: https://github.com/dutchcoders/transfer.sh/issues/450
