### ISSUE TITLE
Feature: skip auth from specific IP

### ISSUE THREAD

**Issue by michaelscl** [dutchcoders/transfer.sh#503]
Hi,

We use the service to exchange files between customers. It would make the work easier to not require upload authentication when accessing from defined IPs.

What do you think?

best regards

Michaels

**Comment by aspacca** [comment]
@michaelscl I see some value indeed, while I'm not sure about the extra complexity in configuration

just an idea at infra level: have you thought about hosting two instances pointing at the same storage, one with and one without upload authentication, and route to the second from the IPs you'd like to whitelist?

**Comment by aspacca** [comment]
> have you thought about hosting two instances pointing at the same storage, one with and one without upload authentication, and route to the second from the IPs you'd like to whitelist?

hello @michaelscl where you able to try this solution?

**Comment by toastie89** [comment]
@aspacca nice idea, I will give it a try

**Comment by toastie89** [comment]
@aspacca, thanks for the workaround!
Having one container with `HTTP_AUTH_USER` and another with `IP_WHITELIST` pointing both to the same storage works fine.

**Comment by michaelscl** [comment]
@aspacca Yes, this is a partial solution for me. For the convenience of uploading from our lan, I didn't want to use HTTP_AUTH at all.

**Comment by aspacca** [comment]
@michaelscl 
as I said my main concern was about complexity of the configuration.

I think a solution migth be to add `NO_HTTP_AUTH_FROM_WHITELIST`

**Comment by aspacca** [comment]
@michaelscl do you think the provided solution at infra level is satisfying?

I will look into adding `NO_HTTP_AUTH_FROM_WHITELIST` in case

**Comment by michaelscl** [comment]
> @michaelscl do you think the provided solution at infra level is satisfying?

I think YES, if the implementation is easy.

**Comment by aspacca** [comment]
> I think YES, if the implementation is easy.

I was talking about this solution:
> have you thought about hosting two instances pointing at the same storage, one with and one without upload authentication, and route to the second from the IPs you'd like to whitelist?

**Comment by michaelscl** [comment]
> have you thought about hosting two instances pointing at the same storage, one with and one without upload authentication, and route to the second from the IPs you'd like to whitelist?

Yes, but this is such a noodle solution. As I wrote. This whole thing is just a suggestion. It's up to you if you decide to implement it or not.

**Comment by aspacca** [comment]
@michaelscl #538 in the case an IP already passed the IP filters authorise automatically for upload

not sure how useful it is. if you currently use the ip filter but you still set an http auth it means you want to differentiate two sets of ip filter lists: the one for get request and the one for upload requests

indeed I'm going to refactor the code in PR and provides a separated http auth ip filter lists because it is the only thing that makes sense
