### ISSUE TITLE
Would you mind adding an option to paste uri on the clipboard?

### ISSUE THREAD

**Issue by voyeg3r** [dutchcoders/transfer.sh#510]
I would like to have an option we could enable and get the final uri in the clipboard and a notify-send telling me that.

**Comment by aspacca** [comment]
hello @voyeg3r I don't know notify-send, cam you explain what's it?

as for copy to clipboard:
`curl --upload-file ./hello.txt https://transfer.sh/hello.txt |pbcopy`

that's on mac, there must be an equivalente of `pbcopy` on other platform

**Comment by tnfru** [comment]
Linux equivalent is to pipe to xlip:

`transfer foo | xclip -selection clipboard` will do the trick.

**Comment by aspacca** [comment]
@voyeg3r I'm going to close the issue.

Feel free to re-open if it's not solved for you
