### ISSUE TITLE
Main site is being used to distribute malware

### ISSUE THREAD

**Issue by eliasrm87** [dutchcoders/transfer.sh#513]
Hi, apologies if this is not the correct place to report about this issue, but I haven't been able to find another way.

I found that there is a web page called gimp[.]monster liking to malware stored at transfer[.]sh/get/mbckh4/Setup.exe
It looks like the platform has not means to report malicious files.

Regards

**Comment by stefanbenten** [comment]
Hello @eliasrm87,

There is a contact us button for these kind of requests. 
The file has been removed quite some time ago already.

Thank you kindly for reporting!
