### ISSUE TITLE
Error 413

### ISSUE THREAD

**Issue by jm33-m0** [dutchcoders/transfer.sh#515]
I did a search and found it might be a size limit issue, then I looked at the [README](https://github.com/dutchcoders/transfer.sh#usage-1), which is extremely confusing.

How should I pass those "parameters" to `transfer.sh` or its docker container? According to "usage" table it looks like I should use environment variables but passing `MAX_UPLOAD_SIZE` didn't work.

**Comment by aspacca** [comment]
@jm33-m0 how do you run the service?
it's either setting `MAX_UPLOAD_SIZE` env variable or passing `--max-upload-size` as paramater directly to transfer.sh binary

**Comment by jm33-m0** [comment]
I tried both and they didn't solve the problem. My setup was docker container on a raspberry pi, haven't seen such error on x86_64 platform though.

**Comment by aspacca** [comment]
@jm33-m0 still an issue?

can you share the details (systemd unit/init script, docker/docker compose file, whatever) on the raspberry pi?

**Comment by mchalupiak** [comment]
I also have this same issue. Flag or env variable, it doesn't seem to fix it. I'm running it with `docker run --publish 8888:8888 dutchcoders/transfer.sh:latest --listener :8888 --provider local --basedir /tmp/` and it returns 413 when I try to upload a 38mb log file. I'm also running on a raspberry pi as well, not sure if that is relevant
