### ISSUE TITLE
Whether there is a background

### ISSUE THREAD

**Issue by phpmac** [dutchcoders/transfer.sh#519]
Whether there is a background

**Comment by aspacca** [comment]
what background? where? :)

**Comment by phpmac** [comment]
admin,Where files are kept,

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2022年12月22日 星期四 5:00 下午，Andrea Spacca ***@***.***> 来信：

**Comment by aspacca** [comment]
@phpmac this repo is for the source code used by the service hosted at https://transfer.sh


while @stefanbenten is one of the maintainer of the repo as well as the admin of https://transfer.sh, questions related to the website are more likely to be address using the "contact us" button on the footer of the website

**Comment by phpmac** [comment]
我的意思有没有后台管理系统？

**Comment by stefanbenten** [comment]
The backend storage can be made one of multiple choices being: Storj, S3, GDrive or local storage.
https://transfer.sh is using Storj as backend provider currently.
