### ISSUE TITLE
Abuse report

### ISSUE THREAD

**Issue by birds1338** [dutchcoders/transfer.sh#520]
Some type of malware that spreads through the malicious pip package: `pyrologin`
Link: `https://transfer.sh/XyC0RH/Updater.zip`

**Comment by aspacca** [comment]
cc @stefanbenten 

@birds1338 , this repo is for the source code of the service hosted at https://transfer.sh, and while stefan is one of the maintainer, you'd probably have better chance to reach him through the "Contact us" button on the website footer

**Comment by stefanbenten** [comment]
The file has been taken down, thank you for flagging/reporting.

As @aspacca noted, please use the Contact Us button on the homepage in the future 👍
