### ISSUE TITLE
Can we have powershell variant of `transfer` function?

### ISSUE THREAD

**Issue by thisismygitrepo** [dutchcoders/transfer.sh#524]
On the website [https://transfer.sh/](https://transfer.sh/) , there is `.cmd` and `.sh` scripts for a wrapper function in those respective shells. Can we have one for `.ps1` ?

**Comment by aspacca** [comment]
hello  @thisismygitrepo , I don't know anything about `.ps1`, sorry
If you are able to provide a version of the scripts for it, I will gladly add to the content

**Comment by thisismygitrepo** [comment]
Hi A, actually windows natively support cmd (surprise) so I'm calling the `.cmd` script that you provided with no issue whatsoever.
