### ISSUE TITLE
Transfer speed for hosted instance rather slow

### ISSUE THREAD

**Issue by dillfrescott** [dutchcoders/transfer.sh#526]
I have no right to complain since this is a free hosted service, but I just thought I'd inform you the speed to upload files on `transfer.sh` domain is rather slow, pretty much all the time.

Not sure if this is a physical limit or not.

**Comment by stefanbenten** [comment]
This is a side affect of people abusing it for CDN use. I am actively investigating changing usage policies and prohibit the distribution in that manner.
Its a file sharing, not distribution service after all.

TLDR: The instances are trashed with continous high volume download.
