### ISSUE TITLE
Unable to get image embeds working on self hosted version of transfer.sh

### ISSUE THREAD

**Issue by Chronic-Reflexes** [dutchcoders/transfer.sh#530]
When testing uploads to transfer.sh the uploaded images will have image previews in apps like discord.

But when uploading to my self hosted version the image preview embed will not show up

Any ideas on how i can fix this?

**Comment by Chronic-Reflexes** [comment]
Should also mention that its ssl and under a proxy

**Comment by aspacca** [comment]
@Chronic-Reflexes is this still an issue?

how did you setup ssl? if your certificate is self signed or it has any validity issue it's most likey that the http request that fetches the image will fail

**Comment by stefanbenten** [comment]
@Chronic-Reflexes Any update on this? 
Otherwise we mark it as stale and are going to close it soon.
