### ISSUE TITLE
async upload, download and share

### ISSUE THREAD

**Issue by gedw99** [dutchcoders/transfer.sh#539]
https://github.com/mprimi/nasefa

can do 50 GB on flakey connections. 
has security 

It would be pretty easy to add to the existing CLI...

**Comment by gedw99** [comment]
You can embed the nats server in the transfer.sh server. 
Nats supports it fully.

you get a control plane and a data plane

**Comment by aspacca** [comment]
hello @gedw99

not sure about providing a nats server listener in transfer.sh: unless I've missed something there's no way to keep the same API for it

it would be a totally different application, and nasefa is already doing that :)

**Comment by stefanbenten** [comment]
transfer.sh has a file size limit of 10G currently. For these file sizes it should not be necessary anyway. For selfhosted variants, i suggest to implement yourself and continue running it as a fork alongside. As @aspacca Already said, the usecase and application type differ drastically.
