### ISSUE TITLE
Return http scheme according to upload scheme (non-https support when printing share url)

### ISSUE THREAD

**Issue by darklow** [dutchcoders/transfer.sh#54]
`https` may not be always available or hard to configure if using docker containers etc.
It would be great if URL could be returned with the same http scheme that it was uploaded, now it always return `https` url even if upload was using `http`
Looks like `https` scheme is hardcoded:
https://github.com/dutchcoders/transfer.sh/blob/7986596d2b06020bf0ba65ac1128ee8eedc522a5/transfersh-server/handlers.go#L252
Thanks

**Comment by nl5887** [comment]
Hi Kaspars, could you try this with latest version? ;-)  Should be fixed now.
