### ISSUE TITLE
Taking a long time to preview a video on `transfer.sh` website

### ISSUE THREAD

**Issue by dillfrescott** [dutchcoders/transfer.sh#540]
Not sure if this means I have slow internet today or not, but videos I upload to share with my friend aren't previewing, or at least taking a long time to do so.

![Screenshot 2023-03-16 231212](https://user-images.githubusercontent.com/56714680/225803408-01ff43ad-69b1-4dee-ae76-ecfd3e38402f.png)

**Comment by aspacca** [comment]
> last time it cached the entire file back on the transfer.sh server before you were able to watch/stream it.

that's not true anymore since https://github.com/dutchcoders/transfer.sh/pull/535

I've tested locally with storj as provider and it worked properly

**Comment by stefanbenten** [comment]
@dillfrescott Please recheck if the issue is still present, if i do not hear back within the next 48 hours i am going to close the issue. 👍

**Comment by dillfrescott** [comment]
Ill have to check in a while because I'm a bit busy sorry! Ill just close it for now!
