### ISSUE TITLE
How to change the protocol in "Sample use cases"

### ISSUE THREAD

**Issue by i207M** [dutchcoders/transfer.sh#543]
Hi, thanks for the great app.
I deployed it on my server behind Nginx, but I found that the default protocol in "Sample use cases" is `http`. How can I change it to `https`?

```
# Uploading is easy using curl
$ curl --upload-file ./hello.txt http://example.com/hello.txt
http://example.com/JnGvbixCV0/hello.txt
```

BTW, I don't want the app handling HTTPS certs, so Nginx is a must.
Thanks in advance.

**Comment by aspacca** [comment]
@i207M what do you mean exaclty with "how can I change it to http"? do you mean on the frontend?

the address is built with https://github.com/dutchcoders/transfer.sh/blob/main/server/handlers.go#L740 and used in the frontend https://github.com/dutchcoders/transfer.sh-web/blob/master/src/index.html#L46

if you make a plain `http` request, it will show `http`, if you make an `https` one it will show `https`

you can use nginx and letsencrypt to have nginx managing `https` and proxy to the app in plain `http`
see a sample config here: https://github.com/dutchcoders/transfer.sh/issues/458#issuecomment-1008632316

**Comment by i207M** [comment]
Thanks for your help.

The underlying issue is, user --https--> nginx --http--> transfer.sh, so the backend receives request in http protocol. And the way to indicate it to use https is to add this line to nginx config:

```
proxy_set_header X-Forwarded-Proto https;
```

Now the scheme of the web address is https.
