### ISSUE TITLE
It is good to add newline at the end of response link

### ISSUE THREAD

**Issue by ochaton** [dutchcoders/transfer.sh#549]
transfer.sh is wonderfully convenient to use as simple private file hosting to move files from server to server.
Usually, file is uploaded using `curl`, ex: `curl -T </path/to/file> <transfer_sh_endpoint>` but created link is returned without newline, so it is not easy to copy.

Many users, I suppose, add extra flags `curl -T </path/to/file> -w '\n' <transfer_sh_endpoint>` but it is not comfortable.

Is it okey, to add newline to the response?

**Comment by aspacca** [comment]
hello @ochaton , long time discussed: we won't make any change on the backend.
there's plenty of options for users to add the newline on the client side, sorry :)

**Comment by aspacca** [comment]
> but created link is returned without newline, so it is not easy to copy.

indeed it's easy with 
```
curl -T </path/to/file> <transfer_sh_endpoint> | pbcopy
```

(that's for mac, there are equivalente on other platform)
