### ISSUE TITLE
Upload not work, stuck on 0%

### ISSUE THREAD

**Issue by zell180** [dutchcoders/transfer.sh#554]
Hi, i'm try to upload from website and rest api but upload not work and stuck on 0%

**Comment by stefanbenten** [comment]
Hello @zell180 ,

would you mind giving a little bit of information like an error message or related?
The originating country would also be helpful to troubleshoot, since we still have some geoblocked countries due to abuse.

**Comment by zell180** [comment]
Hi, country is italy, no message, only stuck on 0% and today is impossible to reach

**Comment by stefanbenten** [comment]
Please try again now, since the service is restored. Reopen if it doesnt work 🙏
