### ISSUE TITLE
We cannot reach transfer.sh

### ISSUE THREAD

**Issue by itseyup** [dutchcoders/transfer.sh#556]
Hello, I have been using transfer.sh on some of my softwares to upload files. I/our softwares cannot reach to transfer.sh and upload files.
My country: Turkey
Tested servers: Turkey, US

**Comment by skaerf** [comment]
Having the same issue from United Kingdom

**Comment by mtr1012** [comment]
Same issue from Vietnam

**Comment by zell180** [comment]
Same issue from italy

**Comment by dingye18** [comment]
Same issue from China

**Comment by AndreasKueck** [comment]
Sama problemo en Germanujo.

**Comment by stefanbenten** [comment]
We are currently working with the provider to bring back the service. Thank you everyone for the patience.

**Comment by Ever4engel** [comment]
tried in france same issue, same in africa countries (tried with a vpn)

**Comment by rojenzaman** [comment]
Same issue from Turkey

**Comment by Nil0375** [comment]
Same issue from Taiwan

**Comment by MarkCallow** [comment]
Same in Japan though I can ping transfer.sh (144.76.136.153).

**Comment by cdalinghaus** [comment]
"You only realize the importance of someone when they are gone."

This tool is amazingly useful, thanks for keeping it running

**Comment by rokibhasansagar** [comment]
Unable to access site from Bangladesh as well 😭

**Comment by Happy-ArthurYang** [comment]
Hi, Is there an estimation for the back of service?

**Comment by fennectech** [comment]
Connection refused from USA

**Comment by 4cq2** [comment]
confirmed:

~~~
> curl -v transfer.sh
*   Trying 144.76.136.153:80...
* connect to 144.76.136.153 port 80 failed: Connection refused

> curl -v https://transfer.sh
*   Trying 144.76.136.153:443...
* connect to 144.76.136.153 port 443 failed: Connection refused
~~~

**Comment by Skillkiller** [comment]
Unable to access site from germany

**Comment by NotGabry** [comment]
unable (again) to access transfer.sh from italy

**Comment by aidanlok** [comment]
Still down from the USA. https://temp.sh/ is a working alternative, as mentioned above.

**Comment by marcelstoer** [comment]
How about https://transfersh.com/? Somehow associated with https://transfer.sh other than obviously running the same software?

**Comment by stefanbenten** [comment]
@marcelstoer https://github.com/dutchcoders/transfer.sh#disclaimer

**Comment by stefanbenten** [comment]
We are still working with the provider to restore the service. Hopefully within the next 2-3 days, the service is restored. Thanks everyone for the patience.

**Comment by zell180** [comment]
Thank you. for a free service it is the least to thank

**Comment by fennectech** [comment]
Thank you :D.

**Comment by dillfrescott** [comment]
Hopefully soon! :)

**Comment by dillfrescott** [comment]
Stumbled upon `https://transfersh.com/`. Is this official?

**Comment by fennectech** [comment]
Unlikely.   Transfer.sh is a free and Open Source project that can be stood up by anyone with a server and an internet connection.  Sent from my iPadOn 12. Jun 2023, at 03:35, Cross ***@***.***> wrote:﻿
Stumbled upon https://transfersh.com/. Is this official?

**Comment by stefanbenten** [comment]
The service is back up and running. There will be some modifications to it soon, but for the time please enjoy the service again!

**Comment by AwesomeKalin** [comment]
It's happening again, although this time it's my fault for uploading lots of small files

**Comment by Skillkiller** [comment]
I have no problem reaching the website from Germany @AwesomeKalin

**Comment by stefanbenten** [comment]
> It's happening again, although this time it's my fault for uploading lots of small files

The server does not have any issues based on monitoring or logs. I have restarted it a couple of times to increase malware scanning levels, etc.

**Comment by cayenne17** [comment]
> Did it crash again? @stefanbenten

De mon côté ça marche.

Il faut mettre HTTPS et pas juste HTTP. je vois que ça répond pas en HTTP port 80. 

Je ne sais pas si c'est normal @stefanbenten ?

**Comment by cayenne17** [comment]
> Did it crash again? @stefanbenten

It works for me.

You have to put HTTPS and not just HTTP. I see that it doesn't respond in HTTP port 80.

I don't know if this is normal @stefanbenten ?

**Comment by itseyup** [comment]
> > Did it crash again? @stefanbenten
> 
> It works for me.
> 
> You have to put HTTPS and not just HTTP. I see that it doesn't respond in HTTP port 80.
> 
> I don't know if this is normal @stefanbenten ?

It doesn't respond with HTTPS too. Im in Turkey. I tried with servers from Turkey and It doesn't respond too.

**Comment by aidanlok** [comment]
Can confirm, does not work from USA either, using HTTP or HTTPS.

**Comment by Skillkiller** [comment]
The website is also not accessible from Germany. At 3 p.m. the site was still reachable.

**Comment by cayenne17** [comment]
it doesn't work for me either. it can't resolve the `transfer.sh` domain name.

it seems to be a problem with the NIC of the `.sh` zone

```
 dig @1.1.1.1  trasfer.sh. +trace

; <<>> DiG 9.16.42-Debian <<>> @1.1.1.1 trasfer.sh. +trace
; (1 server found)
;; global options: +cmd
.                       514782  IN      NS      a.root-servers.net.
.                       514782  IN      NS      b.root-servers.net.
.                       514782  IN      NS      c.root-servers.net.
.                       514782  IN      NS      d.root-servers.net.
.                       514782  IN      NS      e.root-servers.net.
.                       514782  IN      NS      f.root-servers.net.
.                       514782  IN      NS      g.root-servers.net.
.                       514782  IN      NS      h.root-servers.net.
.                       514782  IN      NS      i.root-servers.net.
.                       514782  IN      NS      j.root-servers.net.
.                       514782  IN      NS      k.root-servers.net.
.                       514782  IN      NS      l.root-servers.net.
.                       514782  IN      NS      m.root-servers.net.
.                       514782  IN      RRSIG   NS 8 0 518400 20230905050000 20230823040000 11019 . aCZT4HsmPvL/A4oe3rtFYjlt7L7SZHmquR0I1pCx28qvuqbz3aDOR0jx +2ZtVF/48qI7vnYfd1BNtBFMYiuWIAxX8XUQlAoG38IOoVv+uo/00JR1 K5+AVaOTcITKQKpmKjfGPLyo5dXEoU/YGSBq2ok4E6VH9+GKGw+AkujW jMYhgL5v2c71EhlPf9HtNAsrb5w4rVY8e7k/sjkWq/c9jt9JRRZkTs6K kelQzD4dk4IPZrOHgifEN9e6TJnMbdFWHbgOWDf0tnILc2iC4ROrfCBH ab0VlnZnM/QoBiiNoCAY7fo0/u8I8lstRh4roirI5alPJhEgO7bOME7o iNuJqA==
;; Received 1097 bytes from 1.1.1.1#53(1.1.1.1) in 12 ms

sh.                     172800  IN      NS      a0.nic.sh.
sh.                     172800  IN      NS      a2.nic.sh.
sh.                     172800  IN      NS      b0.nic.sh.
sh.                     172800  IN      NS      c0.nic.sh.
sh.                     86400   IN      DS      55297 8 2 BA339AD6E081DAD292A3F473CBDD5ADC53A0222769A7C6125F506DD6 A813787F
sh.                     86400   IN      RRSIG   DS 8 1 86400 20230905050000 20230823040000 11019 . N6JXxzha/HXECGSseC48n3VdrNu0AYF6iHih0puku/cYr2uBhR/xNmw4 kq2fLd3BO6xT/yHFKzedPbgSLc8x4sTIMx70Fj53Ts7gmMIwgwe8jMci BRE08es6qYpR/RcHT0UZ5QR3J3/2v89Kzd1uMaf9rpM2STHfgdF2V+wq WuG5ume6tg/l/xMGQZ1+Q++KBftJlzPC4s86NSHJbKtQASQX77UPY8bw vVkV4hQKMQXqhQJVCIb9sYxH08vARPkNd8Npu5Qt9Z3RTyWqU189SqJE 2SBP1+SplshL6aQBaVanKOL6Hgqv812kDX2JqE82ZN4vNwMBc7VLNQT5 elvXQw==
;; Received 622 bytes from 192.58.128.30#53(j.root-servers.net) in 28 ms

sh.                     3600    IN      SOA     a0.nic.sh. hostmaster.donuts.email. 1692815488 7200 900 1209600 3600
sh.                     3600    IN      RRSIG   SOA 8 1 3600 20230913183816 20230823173816 64143 sh. shL8NTPUiYn54dor9IomHqPpVwg2GY7ZYQn7FowOPy6n+O0pONOET7xE 6ljXRIM3hIPV+vRmtID2hcgSoYz0w8/LalrxaXonmE55cYMJ2GzeX7Oc C3YDDGhZ/2Orj1Ed4orjNeoXZSARZ7lbvkzr32uUSsFLDj5Wm02aOOym 9z8=
mci9ncnblgquoevrhl6iu1oet1rqmea4.sh. 3600 IN NSEC3 1 1 10 332539EE7F95C32A MCUHLDDFR15GCRPF6MF9NN9S81FKSBLO NS SOA RRSIG DNSKEY NSEC3PARAM
mci9ncnblgquoevrhl6iu1oet1rqmea4.sh. 3600 IN RRSIG NSEC3 8 2 3600 20230913183816 20230823173816 64143 sh. UW/5Iwpzdfg4MeVsN1EC2NNz+eFWcTzP9dW5w4I5i8j28Gv9ixSqZJ9a d/eiPW/6B09jfUTZ8q1eN3PhjZZy+wIjvardczCj7aETyDJa6qXbUes+ EhA8aVXhwYLXLIAZJS1e5OiTk8o1NcdhWyYSjI1Lthv0Tk1Tlj7QT9au XCE=
utuqajc8hhtogl19ehrj09a2va2u07p2.sh. 3600 IN NSEC3 1 1 10 332539EE7F95C32A UU6UK2O7J9DVBPSKVB9HARLLVLHN6GMV NS DS RRSIG
utuqajc8hhtogl19ehrj09a2va2u07p2.sh. 3600 IN RRSIG NSEC3 8 2 3600 20230907011414 20230817001414 64143 sh. psLV3XKJT7lJTC4BT6xL3eEAWthQQYXlEewiHlRGzsThxLaSsYRyqDmd MLc2q6S/s4XN7mequRRM2omlBpJ7frW3DjawogxET0FPZu/LqdPEEr6E XmC7sdzD66t37ztG1zXeJvn+oaEO4ZmPT1bQHHXyoCn3kZRJ1dpldUmy nLo=
vchv64u1cf3r88km2cd4v07veorlllqr.sh. 3600 IN NSEC3 1 1 10 332539EE7F95C32A VCRC8NQGIC2K2KIPOMARUI6K8Q98RP1T NS DS RRSIG
vchv64u1cf3r88km2cd4v07veorlllqr.sh. 3600 IN RRSIG NSEC3 8 2 3600 20230907011414 20230817001414 64143 sh. bxWq0wxXcNik4un249wSCwhs60vpJeAVBHnDv/1ingY9fRl9lhaJr7zN o3AKD6LHtHAKlxCnH23Uy5rrhblMvnbm27fLMdVjBS9kzUbynOFw0KZj tCYzRCOr53cm4Fqa7l+n5A8E1GTwiNRlHGWa0NR2l6CDLUBPRae2C8b5 neo=
;; Received 1015 bytes from 65.22.161.9#53(b0.nic.sh) in 24 ms
```
