### ISSUE TITLE
HTTP_AUTH_USER / HTTP_AUTH_PASS ignored

### ISSUE THREAD

**Issue by odoucet** [dutchcoders/transfer.sh#563]
Hello,
It appears HTTP_AUTH_USER  and HTTP_AUTH_PASS are not doing anything (when used as docker container).
I was expecting an authentication to be required on file uploads when these two variables are present, but nothing happens and everyone can upload a file without auth.
I'm wondering if I'm using it correctly ...

**Comment by aspacca** [comment]
@odoucet can you please share how do you launch your docker container?
either cli command line for `docker run`, your docker-compose file, or whatever? :)

**Comment by odoucet** [comment]
Thanks! I'll wait for https://hub.docker.com/r/dutchcoders/transfer.sh to be updated and I'll confirm to you if it is fixed :)
