### ISSUE TITLE
curl doesn't return download url

### ISSUE THREAD

**Issue by Spacelight42** [dutchcoders/transfer.sh#572]
when I upload the file with curl, I get no response, if I used curl with -v flag, I get at least x-url-delete, so I can guess the download url from that, but without -v I am not able to get the hash for the download url

**Comment by aspacca** [comment]
@Spacelight42 could you please share the full curl command you run and the system you run on?
thanks

**Comment by Spacelight42** [comment]
short version:
`$ curl --progress-bar --interface eth0 --upload-file 20230623_121152.mp4 https://transfer.sh/ltw.mp4                                                                    
spacelight@raspberrypi:/media/flash 
$`

with the -v option (I replaced the hashes in the url by ***):
`curl -v --progress-bar --interface eth0 --upload-file 20230623_121152.mp4 https://transfer.sh/ltw.mp4                                                                 
*   Trying 144.76.136.153:443...                                                                                                                                                                            
* Connected to transfer.sh (144.76.136.153) port 443 (#0)                                                                                                                                                   
* ALPN, offering h2                                                                                                                                                                                         
* ALPN, offering http/1.1      
* successfully set certificate verify locations:                                                                                                                                                     [28/82]
*  CAfile: /etc/ssl/certs/ca-certificates.crt                                                                                                                                                               
*  CApath: /etc/ssl/certs                                                                                                                                                                                   
* TLSv1.3 (OUT), TLS handshake, Client hello (1):                                                                                                                                                           
* TLSv1.3 (IN), TLS handshake, Server hello (2):                                                                                                                                                            
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):                                                                                                                                                    
* TLSv1.3 (IN), TLS handshake, Certificate (11):                                                                                                                                                            
* TLSv1.3 (IN), TLS handshake, CERT verify (15):                                                                                                                                                            
* TLSv1.3 (IN), TLS handshake, Finished (20):                                                                                                                                                               
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):                                                                                                                                                 
* TLSv1.3 (OUT), TLS handshake, Finished (20):                                                                                                                                                              
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256                                                                                                                                                     
* ALPN, server accepted to use h2                                                                                                                                                                           
* Server certificate:                                                                                                                                                                                       
*  subject: CN=transfer.sh                                                                                                                                                                                  
*  start date: Jun 15 21:30:03 2023 GMT    
*  expire date: Sep 13 21:30:02 2023 GMT                                                                                                                                                             [12/82]
*  subjectAltName: host "transfer.sh" matched cert's "transfer.sh"                                                                                                                                          
*  issuer: C=US; O=Let's Encrypt; CN=R3                                                                                                                                                                     
*  SSL certificate verify ok.                                                                                                                                                                               
* Using HTTP2, server supports multi-use                                                                                                                                                                    
* Connection state changed (HTTP/2 confirmed)                                                                                                                                                               
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0                                                                                                                            
* Using Stream ID: 1 (easy handle 0x1017280)                                                                                                                                                                
> PUT /ltw.mp4 HTTP/2                                                                                                                                                                                       
> Host: transfer.sh                                                                                                                                                                                         
> user-agent: curl/7.74.0                                                                                                                                                                                   
> accept: */*                                                                                                                                                                                               
> content-length: 411181079                                                                                                                                                                                 
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!

> content-length: 411181079
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< content-type: text/plain
< server: Transfer.sh HTTP Server
< x-made-with: <3 by DutchCoders
< x-served-by: Proudly served by DutchCoders
< x-url-delete: https://transfer.sh/***/ltw.mp4/***
< content-length: 38
< date: Thu, 13 Jul 2023 07:57:48 GMT
< 
* Connection #0 to host transfer.sh left intact
`



I get the same result for:
Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
and
Linux ***-HP-ZBook-15-G3 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aspacca** [comment]
closing as stale
