### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ShahrukhAbrar** [dutchcoders/transfer.sh#575]
transfer.sh is down

**Comment by KevanGP** [comment]
It is.
I'm not the developer, just someone who knows someone else who uses it...
They think it's a DNS issue, maybe the provider took issue with something a user shared on the service. Or maybe the service just shut down...

If the person I talked to is right, if you know the IP address of the server transfer.sh uses, you might try that.

**Comment by laoclos** [comment]
seems there is a transfersh.com, not sure who is hosting this

**Comment by stefanbenten** [comment]
> seems there is a transfersh.com, not sure who is hosting this

https://github.com/dutchcoders/transfer.sh#disclaimer

**Comment by stefanbenten** [comment]
We are awaiting input from the owner (@nl5887) of the actual domain, since it is a DNS problem.

**Comment by stefanbenten** [comment]
Website is available again.

**Comment by stefanbenten** [comment]
HTTP itself or in your case HTTPS redirect is not setup on purpose, since a lot of malware distribution has been relying on not needing SSL capabilities.

**Comment by ShahrukhAbrar** [comment]
The website is still down in my country (Pakistan). 
![image_2023-08-29_170925234](https://github.com/dutchcoders/transfer.sh/assets/66548752/eda618b0-52b8-4ed5-9973-6ff5b3aeb949)

**Comment by stefanbenten** [comment]
The service/host has an updated version of its geoblocking deployed, which currently sadly has to block the following countries due to abuse:
`RU,CN,PK,KP,TJ,TM,TR,JD,UA`

**Comment by ShahrukhAbrar** [comment]
I see. Is there any chance of reviewing this geoblock in future for these countries?

**Comment by KevanGP** [comment]
@ShahrukhAbrar There are ways to get around this block, such as a VPN, but sadly they cost money most of the time--at least the good ones. I recommend ExpressVPN.
