### ISSUE TITLE
How can I manage files uploaded?

### ISSUE THREAD

**Issue by rty813** [dutchcoders/transfer.sh#577]
As the number of uploaded files increases, storage is becoming insufficient. I need to view the files that users have uploaded and delete the outdated ones.

**Comment by stefanbenten** [comment]
Please look at the following flag options:

- purge-days
- purge-interval

Both should do exactly what you want, delete data after a certain period (days) and checks on a given interval for it.

**Comment by rty813** [comment]
What if I didn't set purge-days and purge-interval?

**Comment by stefanbenten** [comment]
Then there is no provided way by the binary to traverse the data. Depending on the provider used, you'll need to write yourself a script to iterate over the data.

**Comment by rty813** [comment]
I comprehend, thank you.
