### ISSUE TITLE
is http://transfer.sh/ down?

### ISSUE THREAD

**Issue by dimovnike** [dutchcoders/transfer.sh#59]

**Comment by MrSadoo** [comment]
Doesn't open up for me!

**Comment by omgbox** [comment]
its working Fri 19 Aug 2016.  uploaded 800mb

**Comment by nl5887** [comment]
I'll close this issue. We've made some changes to the infra, and no issues anymore.

**Comment by vadi2** [comment]
Seems to be an issue again for at least the last 7 hours.
