### ISSUE TITLE
Could not save metadata

### ISSUE THREAD

**Issue by nt74** [dutchcoders/transfer.sh#594]
I experience this issue right now. Same issue as [#482](https://github.com/dutchcoders/transfer.sh/issues/482)

> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * We are completely uploaded and fine
> < HTTP/2 500 
> < content-type: text/plain; charset=utf-8
> < server: Transfer.sh HTTP Server
> < x-content-type-options: nosniff
> < x-made-with: <3 by DutchCoders
> < x-served-by: Proudly served by DutchCoders
> < content-length: 24
> < date: Tue, 19 Dec 2023 14:17:55 GMT
> < 
> Could not save metadata
> * Connection #0 to host transfer.sh left intact

**Comment by stefanbenten** [comment]
Issue is unrelated to #482, and just a side effect of it not allowing new uploads to due abuse investigation.
Similar to #589 .

**Comment by tobbi** [comment]
This issue re-emerged for me.

**Comment by mrGRINCH** [comment]
Will transfer.sh be coming back?

**Comment by KaKi87** [comment]
Here are alternate instances I found by searching `"Easy file sharing from the command line"` :

- https://transfer.whalebone.io/
- https://transfer.adttemp.com.br/
- https://transfersh.wolke.img.univie.ac.at/
- https://big.tarr.hu/
- https://tar.tn/

I've been using the first one, I don't know whether the other ones work.

**Comment by stefanbenten** [comment]
As soon as investigation and reports have been made, the service will return.

**Comment by KaKi87** [comment]
@dutchcoders Why was my comment removed, and without warning, no less ? Did I violate some rule ? Isn't the whole point of a self-hostable app to index instances so that others can be used when the main one is out of service ?

**Comment by stefanbenten** [comment]
We are removing links to other instances for safety/security purposes of the users. We had several events before where those sites where malicious.

**Comment by mckaygerhard** [comment]
i wish to said that yes transfer.sh can be allow abuse process but is a great sergvice adn i hope that will never ends.. thanks guys for all your efforts

**Comment by KaKi87** [comment]
> We are removing links to other instances for safety/security purposes of the users. We had several events before where those sites where malicious.

Well, since it keeps going down, I would like to strongly suggest reconsidering.

Whatever has to be done to certify the non-maliciousness of instances should he done, for the sake of users in need of this service.

Thanks

**Comment by sylware** [comment]
I have never abused transfer.sh as far as I know.

I guess because I am trying to upload a elf/linux binary? This is a libSDL3 for dota2 (and cs2) including some fixes for alsa[dmix].

Shall I give it another try?

**Comment by stefanbenten** [comment]
The downtime is affecting all users, not just you. Until investigation with authorities is completed, the instance will remain shutdown/non functional for further uploads.

**Comment by sylware** [comment]
Ok! I did not understand the service has been completely shutdown because under police investigation!

(it seems that any non-big-tech service which can be used without a big tech browsers gets into trouble)

**Comment by sysfu** [comment]
Always frustrating when bad actors through their behavior end up ruining everything what was cool about the original spirit of the Internet Hope to see the service come back soon. Just tried again today and it's down. Is there some official status page where we can notifications when it does? Something like statuscake?

**Comment by mckaygerhard** [comment]
> Always frustrating when bad actors through their behavior end up ruining everything what was cool about the original spirit of the Internet Hope to see the service come back soon. Just tried again today and it's down. Is there some official status page where we can notifications when it does? Something like statuscake?

There are two negative points here... that I have already reported before:

1. transfersh is **based on a technology that cannot be hosted by 3th party** except using the latest technology, which apart from that **cannot be used in free hosting... making it difficult to deploy by third parties** like the most common LAMP or free hosts.
2. transfersh it was previously proposed to include delivery by mail and to limit the public service... this was detailed but it was never understood... when you force someone to give data this character retracts... what does it mean, that if someone wants send or receive anonymously you will have to pay someone but if you use it for free you will be limited, otherwise use telegram

i again said to developers thanks for the most easy to use transfering sharing env the current only one that allows console downloading.. but you developers should considering use technology that dont depends on external resources.. this last is pretty important to give a good way to life.. 

**real case: https://gitlab.com/mojo42/Jirafeau not so easy to deploy as a nodejs based project but easy deployable in any free service**

**Comment by KaKi87** [comment]
> transfersh is based on a technology that cannot be hosted by 3th party except using the latest technology

What ? All you need is Docker.

> free hosts

Hosting files on free hosts is worse than hosting files on GAFAM cloud in terms of privacy.

> https://gitlab.com/mojo42/Jirafeau not so easy to deploy as a nodejs based project

What ? It's a PHP-based project.

**Comment by KaKi87** [comment]
@hyder365

As you can see from the past comments, I tried to share some here, but that was removed :

> We are removing links to other instances for safety/security purposes of the users. We had several events before where those sites where malicious.

Maybe instead I should share my trick for finding instances : search `"Easy file sharing from the command line" + "Upload using cURL"` on Google.

**Comment by trikko** [comment]
@stefanbenten the traceroute ends like this:
```
 [...]
 6  ae3-1.fra20.core-backbone.com (80.81.192.187)  27.548 ms corebackbone-AS33891.mix-it.net (217.29.66.10)  22.705 ms ae1-0.lon10.core-backbone.com (195.66.224.238)  33.681 ms
 7  ae1-2014.nbg40.core-backbone.com (81.95.9.14)  36.331 ms  36.563 ms  20.980 ms
 8  core-backbone.hetzner.com (80.255.9.22)  28.100 ms core-backbone.hetzner.com (81.95.15.6)  28.385 ms  28.710 ms
 9  core21.fsn1.hetzner.com (213.239.254.221)  22.212 ms core22.fsn1.hetzner.com (213.239.254.241)  37.594 ms core21.fsn1.hetzner.com (213.239.254.217)  75.311 ms
10  blocked.hetzner.com (88.198.255.174)  50.352 ms  49.933 ms  43.699 ms
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  blocked.hetzner.com (88.198.255.174)  2441.778 ms !X  2550.102 ms !X *
```

That blocked.hetzner.com sounds bad... Is hetzner.com your hosting?

**Comment by cyflux** [comment]
if you want file sharing in terminal, 
try https://github.com/file-kiwi/node?tab=readme-ov-file#cli-usage

**Comment by KaKi87** [comment]
Or, you can use third-party instances, using the trick I mentioned earlier, or find the list I made from said trick, which I posted as a GitHub Gist and an article on my blog.

PS : file.kiwi is proprietary.
