### ISSUE TITLE
Transfer.sh Down?

### ISSUE THREAD

**Issue by 0PandaDEV** [dutchcoders/transfer.sh#609]
Is the official transfer.sh instance down? Because I can not upload any files and the certificates also no longer work on all of my devices even though I enabled self-signed certificates.

https://www.saashub.com/transfer-sh-status

**Comment by stefanbenten** [comment]
It is currently offline due to abuse and related investigations. We do not allow those sort of things and do everything in our ability to stop these people. Shutting the service down until things are resolved is the only way.
For more see #594
