### ISSUE TITLE
"Files stored for X days" NOT reflected on website

### ISSUE THREAD

**Issue by istefy92** [dutchcoders/transfer.sh#629]
Hi,

I deployed your docker container using the environment variable PURGE_DAYS=7 and the local storage.
The website only shows "Files stored forever".

How can I change this to reflect my desired amount of days?

**Comment by aspacca** [comment]
hi @istefy92 , you have to set `PURGE_INTERVAL` as well.
if you have time please open a PR to update the documentation so to make it clear, thanks 👍
