### ISSUE TITLE
how to build this, its not working ubuntu 15.04 server

### ISSUE THREAD

**Issue by omgbox** [dutchcoders/transfer.sh#63]
> not working . go build -o transfersh-server/*.go
> 
> go version
> go version go1.3.3 linux/amd64

~/go/transfer.sh-master# go build -o transfersh-server/_.go
transfersh-server/main.go:43:2: cannot find package "github.com/PuerkitoBio/ghost/handlers" in any of:
    /usr/lib/go/src/pkg/github.com/PuerkitoBio/ghost/handlers (from $GOROOT)
    /root/go/src/github.com/PuerkitoBio/ghost/handlers (from $GOPATH)
transfersh-server/handlers.go:52:2: cannot find package "github.com/dutchcoders/go-clamd" in any of:
    /usr/lib/go/src/pkg/github.com/dutchcoders/go-clamd (from $GOROOT)
    /root/go/src/github.com/dutchcoders/go-clamd (from $GOPATH)
transfersh-server/virustotal.go:30:2: cannot find package "github.com/dutchcoders/go-virustotal" in any of:
    /usr/lib/go/src/pkg/github.com/dutchcoders/go-virustotal (from $GOROOT)
    /root/go/src/github.com/dutchcoders/go-virustotal (from $GOPATH)
transfersh-server/utils.go:35:2: cannot find package "github.com/goamz/goamz/aws" in any of:
    /usr/lib/go/src/pkg/github.com/goamz/goamz/aws (from $GOROOT)
    /root/go/src/github.com/goamz/goamz/aws (from $GOPATH)
transfersh-server/storage.go:14:2: cannot find package "github.com/goamz/goamz/s3" in any of:
    /usr/lib/go/src/pkg/github.com/goamz/goamz/s3 (from $GOROOT)
    /root/go/src/github.com/goamz/goamz/s3 (from $GOPATH)
transfersh-server/utils.go:37:2: cannot find package "github.com/golang/gddo/httputil/header" in any of:
    /usr/lib/go/src/pkg/github.com/golang/gddo/httputil/header (from $GOROOT)
    /root/go/src/github.com/golang/gddo/httputil/header (from $GOPATH)
transfersh-server/handlers.go:54:2: cannot find package "github.com/gorilla/mux" in any of:
    /usr/lib/go/src/pkg/github.com/gorilla/mux (from $GOROOT)
    /root/go/src/github.com/gorilla/mux (from $GOPATH)
transfersh-server/handlers.go:55:2: cannot find package "github.com/kennygrant/sanitize" in any of:
    /usr/lib/go/src/pkg/github.com/kennygrant/sanitize (from $GOROOT)
    /root/go/src/github.com/kennygrant/sanitize (from $GOPATH)
transfersh-server/handlers.go:56:2: cannot find package "github.com/russross/blackfriday" in any of:
    /usr/lib/go/src/pkg/github.com/russross/blackfriday (from $GOROOT)
    /root/go/src/github.com/russross/blackfriday (from $GOPATH)
root@vp34534534:~/go/transfer.sh-master# go run transfersh-server/_.go -provider=local --port 8080 --temp=/tmp/ --basedir=/tmp/ 
transfersh-server/main.go:43:2: cannot find package "github.com/PuerkitoBio/ghost/handlers" in any of:
    /usr/lib/go/src/pkg/github.com/PuerkitoBio/ghost/handlers (from $GOROOT)
    /root/go/src/github.com/PuerkitoBio/ghost/handlers (from $GOPATH)
transfersh-server/handlers.go:52:2: cannot find package "github.com/dutchcoders/go-clamd" in any of:
    /usr/lib/go/src/pkg/github.com/dutchcoders/go-clamd (from $GOROOT)
    /root/go/src/github.com/dutchcoders/go-clamd (from $GOPATH)
transfersh-server/virustotal.go:30:2: cannot find package "github.com/dutchcoders/go-virustotal" in any of:
    /usr/lib/go/src/pkg/github.com/dutchcoders/go-virustotal (from $GOROOT)
    /root/go/src/github.com/dutchcoders/go-virustotal (from $GOPATH)
transfersh-server/utils.go:35:2: cannot find package "github.com/goamz/goamz/aws" in any of:
    /usr/lib/go/src/pkg/github.com/goamz/goamz/aws (from $GOROOT)
    /root/go/src/github.com/goamz/goamz/aws (from $GOPATH)
transfersh-server/storage.go:14:2: cannot find package "github.com/goamz/goamz/s3" in any of:
    /usr/lib/go/src/pkg/github.com/goamz/goamz/s3 (from $GOROOT)
    /root/go/src/github.com/goamz/goamz/s3 (from $GOPATH)
transfersh-server/utils.go:37:2: cannot find package "github.com/golang/gddo/httputil/header" in any of:
    /usr/lib/go/src/pkg/github.com/golang/gddo/httputil/header (from $GOROOT)
    /root/go/src/github.com/golang/gddo/httputil/header (from $GOPATH)
transfersh-server/handlers.go:54:2: cannot find package "github.com/gorilla/mux" in any of:
    /usr/lib/go/src/pkg/github.com/gorilla/mux (from $GOROOT)
    /root/go/src/github.com/gorilla/mux (from $GOPATH)
transfersh-server/handlers.go:55:2: cannot find package "github.com/kennygrant/sanitize" in any of:
    /usr/lib/go/src/pkg/github.com/kennygrant/sanitize (from $GOROOT)
    /root/go/src/github.com/kennygrant/sanitize (from $GOPATH)
transfersh-server/handlers.go:56:2: cannot find package "github.com/russross/blackfriday" in any of:
    /usr/lib/go/src/pkg/github.com/russross/blackfriday (from $GOROOT)
    /root/go/src/github.com/russross/blackfriday (from $GOPATH)

**Comment by nl5887** [comment]
Could you try this with latest version?

**Comment by devpets** [comment]
How to build?
Downloaded master.zip,
running:
transfer@archive:~/transfer.sh/cmd$ cd ..
transfer@archive:~/transfer.sh$ ls
cmd  Dockerfile  extras  LICENSE  lock.json  main.go  manifest.json  README.md  server  Vagrantfile  vendor
transfer@archive:~/transfer.sh$ pwd
/home/transfer/transfer.sh
transfer@archive:~/transfer.sh$ go build -o transfersh main.go
main.go:3:8: cannot find package "github.com/dutchcoders/transfer.sh/cmd" in any of:
        /usr/lib/go-1.6/src/github.com/dutchcoders/transfer.sh/cmd (from $GOROOT)
        ($GOPATH not set)
transfer@archive:~/transfer.sh$

**Comment by aspacca** [comment]
@devpets you need to set `$GOPATH` and have the code in `$GOPATH/src/github.com/dutchcoders/transfer.sh`
see: https://github.com/golang/go/wiki/SettingGOPATH

**Comment by mckaygerhard** [comment]
well quite trange but since go 1.12 gopath are deprecated ? or goroot?

**Comment by aspacca** [comment]
@mckaygerhard none of them, they may be in the future

**Comment by mckaygerhard** [comment]
umm that are interesting, but after read this https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really i think setting gorrot or gopath are a windo-like trick only! and i really this its a valid issue! that will defect and dificult the OS like proper distribution

**Comment by mckaygerhard** [comment]
umm that are interesting, but after read this https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really i think setting gorrot or gopath are a windo-like trick only! and i really this its a valid issue! that will defect and dificult the OS like proper distribution

as the documentation said, now goroot declaration are optional due automatically set to package root, that means: https://golang.org/doc/go1.10#goroot in any proyect must be automatically permit OS software package redistribution so then your proyect must use the current directory. but seems not happened!

**Comment by mckaygerhard** [comment]
umm that are interesting, but after read this https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really i think setting gorrot or gopath are a windo-like trick only! and i really this its a invalid issue! but in any case will defect and dificult the OS like proper distribution...

as the documentation said, GOÄTH are mandatory and only now goroot declaration are optional due automatically set to package root, that means: https://golang.org/doc/go1.10#goroot in any proyect must be automatically permit OS software package redistribution so then your proyect must use the current directory. but seems not happened!
