### ISSUE TITLE
Running in Docker daemon mode

### ISSUE THREAD

**Issue by wicadmin** [dutchcoders/transfer.sh#68]
Most likely I'm misunderstanding something but how do I get this running in daemon mode in Docker? I tried the following but I could not curl a file to port 8085.

`docker run -d -p 8085:8080 --name transfersh transfersh`

Gave this error:

```
curl --upload-file ./test123.txt http://192.168.1.89:8085/
curl: (7) Failed to connect to 192.168.1.89 port 8085: Connection refused
```

OK: was passing the Go params in the wrong place. This works without giving the connection refuse error but the files are not uploaded. i.e.: /tmp/ is empty after the curl command.

`docker run -d -p 8085:8080 --name transfersh transfersh --basedir /tmp/ --provider local`

Logs show this only. Is there a way to up the level to debug?:

```
10/14/2016 12:56:37 PMNumber of CPUs:  2
10/14/2016 12:56:37 PMProfiled listening at: :6060
10/14/2016 12:56:37 PM2016/10/14 16:56:37 Transfer.sh server started. :
10/14/2016 12:56:37 PMlistening on port: 8080
10/14/2016 12:56:37 PMusing temp folder: /tmp
10/14/2016 12:56:37 PMusing storage provider: local
10/14/2016 12:56:37 PM2016/10/14 16:56:37 ---------------------------
```

**Comment by nl5887** [comment]
This looks like everything works fine. The connection refused indicates that curl cannot connect to the web server itself. Does this work without starting it in daemon mode?

**Comment by wicadmin** [comment]
I'm going to close for now.
