### ISSUE TITLE
Please allow for uppercase download URLs

### ISSUE THREAD

**Issue by probonopd** [dutchcoders/transfer.sh#69]
Right now it seems that the download URLs returneed from transfer.sh are always lowercase. Please allow for uppercase characters in download URLs as well.

If that is already possible, please show me how.

**Comment by Arinerron** [comment]
Duplicate issue of https://github.com/dutchcoders/transfer.sh/issues/10

**Comment by nl5887** [comment]
Commit @45bafbe48f44c711e97b5c269254d7c43d42db37 closes this issue
