### ISSUE TITLE
Transfer bashrc enable interpretation of backslash escapes

### ISSUE THREAD

**Issue by gelim** [dutchcoders/transfer.sh#74]
In the bashrc snippet you display here : https://github.com/dutchcoders/transfer.sh/blob/master/transfersh-web/index.html#L153

You probably want to enable interpretation of backslash by changing `echo` to `echo -e`
That would allow to have a properly formatted error messages when no argument is passed to the function.

At the moment it looks like this:
```
$ transfer 
No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md
```

Cheers,
Mathieu

**Comment by nl5887** [comment]
Fixed! thx.
