### ISSUE TITLE
Github Buttons missing on transfer.sh webpage

### ISSUE THREAD

**Issue by c33s** [dutchcoders/transfer.sh#76]
it looks like the embedding of the github buttons is somehow broken. the buttons are missing for me on firefox & chrome because of "unauthenticated sources" 

![trans](https://cloud.githubusercontent.com/assets/649209/21075999/c47e0342-bf20-11e6-82dd-6f0582866ac2.png)

on both browser it is possible to do an unsafe reload which then shows the buttons.

this is because of the changed urls 
```
https://mdo.github.io/github-buttons/github-btn.html?user=dutchcoders&repo=transfer.sh&type=follow&count=true&size=large
```
redirects to
```
http://ghbtns.com/github-btn.html?user=dutchcoders&repo=transfer.sh&type=follow&count=true&size=large
```

https would be working but it looks like it is possible to include it with the correct url:
```
https://ghbtns.com/github-btn.html?user=dutchcoders&repo=transfer.sh&type=follow&count=true&size=large
```

**Comment by nl5887** [comment]
Thx! Fixed.
