### ISSUE TITLE
Customize The Site Layout?

### ISSUE THREAD

**Issue by dinosaw** [dutchcoders/transfer.sh#80]
Is there a way to alter the site layout to one's unique needs? This is a great tool, but the "transfer.sh" branding everywhere confuses our customers who visit it. I'd like to be able to alter it so it looks at least similar to our branding (without of course removing the reference and fork link because we're not trying to steal credit). I'm running this via the Docker container. I can modify the HTML/CSS pages if I could only find them. Thanks!

**Comment by nl5887** [comment]
Sure, you can use the parameter web-path for that. It will overrule the default static files. You can find the web interface to customize here (https://github.com/dutchcoders/transfer.sh-web) by the way.
