### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by nonameolsson** [dutchcoders/transfer.sh#81]
Hi!
Great tool! 

Would it be possible to add password protection to files? 
`transfer --password=mypass myfile.png`

[http://recordit.co/](http://recordit.co/) has password protection and it works pretty nice.

Thanks for developing transfer.sh!

**Comment by rockymadden** [comment]
Tiny CLI interface for transfer.sh that does this: 

```bash
$ transfer upload /path/to/file.log --encrypt --password password
```

https://github.com/rockymadden/transfer-cli
