### ISSUE TITLE
New awesome exemple (URL copied to clipboard)

### ISSUE THREAD

**Issue by heuzef** [dutchcoders/transfer.sh#83]
Thanks for this amazing tools ! New awesome example with alias (.bashrc) :

`transfer() { if [ $# -eq 0 ]; then echo -e "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"; return 1; fi
tmpfile=$( mktemp -t transferXXX ); if tty -s; then basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g'); curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile; else curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ; fi; cat $tmpfile | parcellite -c | sleep 1; rm -f $tmpfile; echo "URL copied to clipboard"; echo; }`

URL will be copied to clipboard via [parcellite](parcellite.sourceforge.net) :)

`> transfer texture.jpg 
######################################################################## 100,0%
URL copied to clipboard
`

**Comment by gingerbeardman** [comment]
you should use `pbcopy` instead as it is a built-in macOS command.

Here's my version

```bash
transfer() { if [ $# -eq 0 ]; then echo -e "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"; return 1; fi
tmpfile=$( mktemp -t transferXXX ); if tty -s; then basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g'); curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile; else curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ; fi; cat $tmpfile | pbcopy | pbpaste; printf '\n'; rm -f $tmpfile; } 
```
