### ISSUE TITLE
QR-code

### ISSUE THREAD

**Issue by danielleontiev** [dutchcoders/transfer.sh#86]
Please, add qr-code with link to the uploaded file on `https://transfer.sh`

**Comment by JtokohZohl** [comment]
`curl -s --upload-file ./file.zip https://transfer.sh/file.zip | qrencode  -t UTF8 -l H -o-`

**Comment by danielleontiev** [comment]
@JtokohZohl it's good but unnecessary in shell. QR code should be on the site because you may want to grab smth from foreign computer using `https://transfer.sh` and the fastest way to do it -- scan QR code on the site, where you upload files.

**Comment by aspacca** [comment]
@danielleontiev how can we add a QR code to the output? either we return some text with a link or an image with the qr code

**Comment by danielleontiev** [comment]
@aspacca I mean QR code when upload using web interface. Directly on site transfer.sh
