### ISSUE TITLE
Ending Lines With "\n"

### ISSUE THREAD

**Issue by Alirezaies** [dutchcoders/transfer.sh#87]
Hello

thank you for this usefull app.

please add "\n" at the end of response as zsh shows `https://transfer.sh/2hWcO/.zshrc%`.

thanks

**Comment by MercuryxLion** [comment]
I solved this "problem" editing the transfer alias in my .bashrc. Using ** && printf '\n'  >> $tmpfile ** 


[Solution.txt](https://github.com/dutchcoders/transfer.sh/files/1129922/Solution.txt)

**Comment by Alirezaies** [comment]
@MercuryxLion thanks, I'll keep this issue open until this solution will be added
+1

**Comment by gingerbeardman** [comment]
+1

**Comment by pepa65** [comment]
Because the output is a URL, it is never going to be confusing to add the newline to the output. In those rare cases, it can always be easily stripped. This is basic usability.

**Comment by robertopc** [comment]
I added an 'echo' in the end of function in the .bashrc
