### ISSUE TITLE
use transfer.sh in other programming language

### ISSUE THREAD

**Issue by shayanzare** [dutchcoders/transfer.sh#88]
Hello.

How can i use transfer.sh **api** in other programming language like ruby and c++?
have lib for this language?

Thanks.

**Comment by Ammadkhalid** [comment]
You can use curl to transfer your file.

**Comment by mitchellurgero** [comment]
Ruby, PHP, C++,C#, etc,etc all support "curl" like http clients. So uploading to transfer.sh using pretty much any language will work fine.

**Comment by retorquere** [comment]
I'm looking to upload a text snippet I have in-code (in Ruby) that I want to upload to transfer.sh; if possible I'd like to do so directly without first writing it to disk. I currently have this:

```
require 'net/http/post/multipart'
require 'net/http'
require 'rest-client'
require 'curb'

# net/http with multipart
uri = URI.parse('https://transfer.sh/')
Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
  req = Net::HTTP::Post::Multipart.new(uri, { "file" => "A nice picture!" })
  puts http.request(req).body.inspect
end

# net/http with put
Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
  req = Net::HTTP::Put.new(uri)
  req.body = "whatever"
  puts http.request(req).body.inspect
end

# restclient
puts RestClient.post('https://transfer.sh/', {:file => 'bar', :multipart => true}).body.inspect

# curb
c = Curl::Easy.new('https://transfer.sh/')
c.multipart_form_post = true
c.http_post([ Curl::PostField.content('file', 'hello') ])
puts c.body_str.inspect
```

but this gets me an empty response body in all those cases. It must be something I'm doing wrong in Ruby, because this python snippet works just fine:

```
import requests
response = requests.post('https://transfer.sh/', files={'travis.md':'baz'})
print(response.text)
```
