### ISSUE TITLE
Add Support for Authenticated Uploads

### ISSUE THREAD

**Issue by Prajjwal** [dutchcoders/transfer.sh#92]
In most personal use scenarios, the user wants to lock down upload access to the server. I can't find anything in your `README` that talks about authentication. It is a matter of adding a single `access_token` to each POST request. Any plans for something like this?

**Comment by kamaln7** [comment]
I can take a stab at implementing something like this. Either pass an "Authentication" header with the key or just a regualar parameter. @dutchcoders—is that alright?

**Comment by Prajjwal** [comment]
@nl5887 I've implemented this. Care to take a look?

**Comment by techburgher** [comment]
It would be nicer, for me, if there were a password prompt when accessing the web site itself, and not simply passed via an extra header.

**Comment by techburgher** [comment]
Here's a BasicAuth "hack", if anyone is interested:

`func LoveHandler(h http.Handler) http.HandlerFunc {
        return func(w http.ResponseWriter, r *http.Request) {
                w.Header().Set("Server", "Panasas HTTP Server 1.0")

                w.Header().Set("WWW-Authenticate", `Basic realm="Restricted"`)

                username, password, authOK := r.BasicAuth()
                if authOK == false {
                        http.Error(w, "Not authorized", 401)
                        return
                }

                if username != "myusername" || password != "mypassword" {
                        http.Error(w, "Not authorized", 401)
                        return
                }

                h.ServeHTTP(w, r)
        }
}
`

**Comment by Prajjwal** [comment]
@techburgher I've already implemented authentication with auth headers in #105. Hasn't been merged in yet, though. You might want to take a look at it.
