### ISSUE TITLE
Can not go back to preview page due to cache overwriting

### ISSUE THREAD

**Issue by programmerjake** [dutchcoders/transfer.sh#94]
If I go to a file-preview page (like <https://transfer.sh/GkNVP/output.png>), then click on the "home" link, if I then try to use the back button in the web browser, it tries to download instead of preview the file.

If I disable the browser cache, the problem goes away.

I'm using Google Chrome 60.0.3112.113 on X11 Linux x86_64.

From what I can tell, the preview page links to itself to display the image, causing the browser to replace the cached copy of the web page with the image because they both have the same URL, then, when I go back to that page, the browser loads the image from the cache instead of the web page.

**Comment by aspacca** [comment]
cannot reproduce
