### ISSUE TITLE
Add support Unicode

### ISSUE THREAD

**Issue by Madji** [dutchcoders/transfer.sh#95]
Please add support Unicode on the file name.
Currently the download doesn't is if the file name contains Unicode

**Comment by sergeevabc** [comment]
I cannot stress enough how crucial this feature request is for non-Latin users and how weird to see and how weird it is to detect its absence in the 21st century. @nl5887, are you there?

**Comment by sergeevabc** [comment]
For example, let’s try to upload the [following photo][1] of VDNH (major exhibition centre and park in Moscow).
Russian filename is ``ВДНХ.jpg``. And Transfer.sh simply does… nothing, i.e. file cannot be uploaded.

[1]: https://nofile.io/f/dYFVNydOfoO/ВДНХ.jpg

**Comment by nl5887** [comment]
Yeah, I understand the necessity and agree that this has to be fixed. 

@sergeevabc  As this is an opensource project it is possible for the community to fix and create PRs. Because it is free and open, no-one can expect me to fix all issues.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by aspacca** [comment]
@sergeevabc , I tried to upload locally a filename with cyrillic chars and I had no issue:
`$ curl --upload-file ./ВДНХ.txt http://127.0.0.1:8080/ВДНХ.txt
http://127.0.0.1:8080/d94Eb/%D0%92%D0%94%D0%9D%D0%A5.txt`

the only outcome is that the filename is urlencoded, that I think is the proper way to go. according to the client you're using to download the file it may or not support unicode in the url

**Comment by sergeevabc** [comment]
@aspacca, ```curl``` is for geeks, the rest use and complain about web interface, i.e. www.transfer.sh.
So there is STILL no way to upload image with Cyrillic chars.

**Comment by aspacca** [comment]
@sergeevabc either you provide some context to your issue or nothing can be done.
also I can address only issues in the codebase, not on the hosting part of transfer.sh
anyway, when I tested with curl I tested both locally and on transfer.sh and there's no problem upload file with cyrillic chars in the name to transfer.sh (https://transfer.sh/AAP2C/%D0%92%D0%94%D0%9D%D0%A5.txt)

**Comment by aspacca** [comment]
you can also use the url with filename not urlencoded: https://transfer.sh/AAP2C/ВДНХ.txt
